"""Data-tree ownership, retention, and disk-budget inventory."""

from __future__ import annotations

import argparse
import fnmatch
import json
import shutil
from dataclasses import asdict, dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from weather.operations.storage_classes import (
    classification_payload,
    delete_gate_for_storage_class,
    storage_class_contracts_payload,
)
from weather.operations.event_day_manifest import summarize_event_day_manifests
from weather.paths import data_path
from weather.reporting.formatting import markdown_table
from weather.schema_registry import schema_version


SCHEMA_VERSION = schema_version("data_retention_inventory")
DEFAULT_DATA_ROOT = data_path()
DEFAULT_OUT = DEFAULT_DATA_ROOT / "backtest" / "data_retention_inventory.json"
DEFAULT_REPORT = DEFAULT_DATA_ROOT / "backtest" / "data_retention_inventory_report.md"
DEFAULT_MIN_FREE_BYTES = 5_000_000_000
DEFAULT_LOOKBACK_HOURS = 24.0
DEFAULT_TOP_N = 25


@dataclass(frozen=True)
class DataRetentionPolicy:
    name: str
    owner: str
    patterns: tuple[str, ...]
    durability: str
    local_ttl: str
    archive_ttl: str
    deletion_requirement: str
    regeneration_path: str
    prune_policy: str
    deletion_requires_review: bool = False
    local_delete_allowed: bool = False


POLICIES = (
    DataRetentionPolicy(
        "snapshots",
        "collection/model/market",
        ("snapshots/**",),
        "irreplaceable live snapshot, feature, source-status, and CLOB evidence",
        "keep active and recent settled days locally; archive older proof-grade folders only after review",
        "permanent external archive for proof-grade live tapes",
        "requires reviewed cleanup manifest before deletion",
        "not regenerable from providers after the fact",
        "delete only from an explicit reviewed manifest; prefer gzip tiering for full-depth books",
        deletion_requires_review=True,
    ),
    DataRetentionPolicy(
        "backtest",
        "reporting/calibration",
        ("backtest/**",),
        "mixed: promotion corpora and reports are durable; row exports may be rebuildable",
        "keep manifests, reports, promotion corpora, and current evidence; review large row exports after 30 days",
        "retain promotion corpora/manifests permanently; large rebuildable CSVs may be externalized",
        "deletion of promotion corpora requires artifact lineage; generated row exports require paired reports",
        "large row exports can usually be rebuilt from retained corpus, artifact, and report",
        "use backtest_artifact_retention cleanup manifest; never delete orphaned evidence by hand",
        local_delete_allowed=True,
    ),
    DataRetentionPolicy(
        "settlements",
        "backtesting/market",
        ("settlements/**",),
        "irreplaceable settlement and label provenance",
        "retain locally with promotion corpora; archive only after review",
        "permanent external archive",
        "requires reviewed cleanup manifest before deletion",
        "not safely regenerable without settlement-source history and manual overrides",
        "delete only from a reviewed manifest",
        deletion_requires_review=True,
    ),
    DataRetentionPolicy(
        "mm_runs",
        "market",
        ("mm_runs/**",),
        "irreplaceable market-making paper/live-forward lifecycle evidence",
        "retain locally through active review",
        "permanent external archive for countable live/paper evidence",
        "requires reviewed cleanup manifest before deletion",
        "not regenerable because quote/fill/markout timing is live-only",
        "delete only from a reviewed manifest after promotion windows close",
        deletion_requires_review=True,
    ),
    DataRetentionPolicy(
        "taker_runs",
        "market",
        ("taker_runs/**",),
        "irreplaceable taker strategy, fill, and settlement evidence",
        "retain locally through strategy bakeoff and settlement finalization",
        "permanent external archive for countable trading evidence",
        "requires reviewed cleanup manifest before deletion",
        "not regenerable because fills and account snapshots are live-only",
        "delete only from a reviewed manifest",
        deletion_requires_review=True,
    ),
    DataRetentionPolicy(
        "ops",
        "operations",
        ("ops/**",),
        "operational reports, status, and local run diagnostics",
        "keep latest statuses and incident evidence; rotate noisy logs after 30 days",
        "archive incident reports with related run evidence",
        "manual review required only for incident evidence; routine status is regenerable",
        "routine health reports are regenerated by daily refresh and fleet observability",
        "rotate only with an incident manifest or after confirming regenerated status exists",
        local_delete_allowed=True,
    ),
    DataRetentionPolicy(
        "provider_caches",
        "sources/model",
        (
            "forecast_archive/**",
            "forecast_history/**",
            "cache/**",
            "open_meteo/**",
            "weather_com/**",
            "source_cache/**",
        ),
        "mostly regenerable provider cache; some forecast archives are evidence",
        "keep recent cache within provider TTL; keep forecast archives used by training until archived",
        "archive forecast snapshots that participate in settled replay evidence",
        "cache deletion is allowed when no replay/promotion artifact references it",
        "regenerate from provider only where API history is available; live-issued forecasts may not be recoverable",
        "delete TTL-expired cache only; do not delete archived forecast snapshots without lineage review",
        local_delete_allowed=True,
    ),
    DataRetentionPolicy(
        "historical_sources",
        "sources",
        (
            "wunderground/**",
            "metar/**",
            "asos/**",
            "ghcnh/**",
            "noaa_ghcnh/**",
            "power/**",
            "nasa_power/**",
            "meteostat/**",
            "eccc/**",
            "eccc_swob/**",
        ),
        "historical weather source rows and provenance manifests",
        "retain canonical source histories locally; archive raw mirrors only after review",
        "permanent archive for raw/provenance source rows",
        "requires source manifest before raw deletion",
        "some provider history is backfillable, but canonical settled-source provenance is not safely assumed regenerable",
        "delete only duplicate raw mirrors after manifest review",
        deletion_requires_review=True,
    ),
    DataRetentionPolicy(
        "reanalysis",
        "sources/calibration",
        ("reanalysis/**",),
        "large gridded/reanalysis source cache and derived sidecars",
        "retain sidecars and latest cache windows; externalize large raw gridded files when manifest-backed",
        "archive raw pressure/gridded files used by trained artifacts",
        "re-download proof required before removing raw NetCDF/GRIB cache",
        "raw gridded files may be re-downloaded when upstream retains the exact vintage; sidecars are rebuildable",
        "externalize raw files with checksums; rebuild sidecars after re-download",
        local_delete_allowed=True,
    ),
    DataRetentionPolicy(
        "logs",
        "operations",
        ("logs/**",),
        "local operational logs",
        "rotate after incident review",
        "archive only incident-linked logs",
        "manual owner review required before deletion",
        "routine logs are not evidence unless referenced by an incident report",
        "rotate with operator approval",
        local_delete_allowed=True,
    ),
)


def _format_bytes(value: int | float | None) -> str:
    if value is None:
        return "-"
    size = float(value)
    units = ("B", "KB", "MB", "GB", "TB")
    index = 0
    while abs(size) >= 1024.0 and index < len(units) - 1:
        size /= 1024.0
        index += 1
    return f"{size:.1f} {units[index]}" if index else f"{int(size)} B"


def _utc_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _load_json(path: str | Path | None) -> dict[str, Any]:
    if not path:
        return {}
    path = Path(path)
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def _matches_any(rel_path: str, patterns: tuple[str, ...]) -> bool:
    return any(fnmatch.fnmatch(rel_path, pattern) for pattern in patterns)


def classify_data_path(rel_path: str) -> DataRetentionPolicy:
    normalized = rel_path.replace("\\", "/")
    for policy in POLICIES:
        if _matches_any(normalized, policy.patterns):
            return policy
    return DataRetentionPolicy(
        "unclassified",
        "owner-review",
        (),
        "unclassified local data",
        "retain until owner review",
        "none until classified",
        "manual owner review required before deletion",
        "unknown",
        "do not delete until classified",
    )


def _policy_delete_gate(policy: DataRetentionPolicy) -> dict[str, Any]:
    if not policy.deletion_requires_review:
        return {
            "status": "NOT_REQUIRED",
            "delete_permission": "allowed_by_policy_with_manifest" if policy.local_delete_allowed else "retain",
            "detail": policy.deletion_requirement,
        }
    return {
        "status": "REVIEW_REQUIRED",
        "delete_permission": "allowed_only_with_reviewed_manifest",
        "detail": policy.deletion_requirement,
    }


def _newest_mtime(paths: list[dict[str, Any]]) -> str | None:
    if not paths:
        return None
    return max(row["modified_at_utc"] for row in paths)


def _file_row(path: Path, root: Path, policy: DataRetentionPolicy) -> dict[str, Any]:
    stat = path.stat()
    rel = path.relative_to(root).as_posix()
    return {
        "path": rel,
        "policy": policy.name,
        "owner": policy.owner,
        **classification_payload(rel),
        "bytes": int(stat.st_size),
        "size_human": _format_bytes(stat.st_size),
        "modified_at_utc": datetime.fromtimestamp(stat.st_mtime, timezone.utc).isoformat(),
    }


def _storage_summary_row(storage_class: str) -> dict[str, Any]:
    return {
        "storage_class": storage_class,
        "file_count": 0,
        "bytes": 0,
        "size_human": "0 B",
        "new_file_count": 0,
        "new_bytes": 0,
        "new_size_human": "0 B",
        "protected_files": 0,
        "protected_bytes": 0,
        "protected_human": "0 B",
        "artifact_families": set(),
        "delete_gate": {},
    }


def build_payload(
    root: str | Path = DEFAULT_DATA_ROOT,
    *,
    min_free_bytes: int = DEFAULT_MIN_FREE_BYTES,
    lookback_hours: float = DEFAULT_LOOKBACK_HOURS,
    top_n: int = DEFAULT_TOP_N,
) -> dict[str, Any]:
    root = Path(root)
    generated_at = datetime.now(timezone.utc)
    cutoff = generated_at - timedelta(hours=float(lookback_hours))
    event_day_manifests = summarize_event_day_manifests(root / "snapshots", check_hashes=False)
    usage_path = root if root.exists() else root.parent
    usage = shutil.disk_usage(usage_path)
    policies = {policy.name: policy for policy in POLICIES}
    summaries: dict[str, dict[str, Any]] = {}
    storage_summaries: dict[str, dict[str, Any]] = {}
    top_dirs: dict[str, dict[str, Any]] = {}
    recent_dirs: dict[str, dict[str, Any]] = {}
    largest_files: list[dict[str, Any]] = []
    recent_files: list[dict[str, Any]] = []
    file_count = 0
    total_bytes = 0

    if root.exists():
        for path in root.rglob("*"):
            if not path.is_file():
                continue
            try:
                stat = path.stat()
            except OSError:
                continue
            rel = path.relative_to(root).as_posix()
            policy = classify_data_path(rel)
            row = _file_row(path, root, policy)
            file_count += 1
            total_bytes += row["bytes"]
            summary = summaries.setdefault(policy.name, {
                "policy": policy.name,
                "owner": policy.owner,
                "file_count": 0,
                "bytes": 0,
                "size_human": "0 B",
                "largest_file": None,
                "new_file_count": 0,
                "new_bytes": 0,
                "new_size_human": "0 B",
                "newest_modified_at_utc": None,
                "delete_gate": {},
            })
            summary["file_count"] += 1
            summary["bytes"] += row["bytes"]
            storage_summary = storage_summaries.setdefault(
                row["storage_class"],
                _storage_summary_row(row["storage_class"]),
            )
            storage_summary["file_count"] += 1
            storage_summary["bytes"] += row["bytes"]
            if row.get("protected"):
                storage_summary["protected_files"] += 1
                storage_summary["protected_bytes"] += row["bytes"]
            if row.get("artifact_family"):
                storage_summary["artifact_families"].add(row["artifact_family"])
            if not summary["largest_file"] or row["bytes"] > summary["largest_file"]["bytes"]:
                summary["largest_file"] = row
            modified = datetime.fromtimestamp(stat.st_mtime, timezone.utc)
            if modified >= cutoff:
                summary["new_file_count"] += 1
                summary["new_bytes"] += row["bytes"]
                storage_summary["new_file_count"] += 1
                storage_summary["new_bytes"] += row["bytes"]
                recent_files.append(row)
                dir_key = rel.split("/", 1)[0]
                recent_dir = recent_dirs.setdefault(dir_key, {"path": dir_key, "file_count": 0, "bytes": 0})
                recent_dir["file_count"] += 1
                recent_dir["bytes"] += row["bytes"]
            dir_key = rel.split("/", 1)[0]
            top_dir = top_dirs.setdefault(dir_key, {"path": dir_key, "file_count": 0, "bytes": 0})
            top_dir["file_count"] += 1
            top_dir["bytes"] += row["bytes"]
            largest_files.append(row)

    for name, summary in summaries.items():
        policy = policies.get(name) or classify_data_path("")
        summary["size_human"] = _format_bytes(summary["bytes"])
        summary["new_size_human"] = _format_bytes(summary["new_bytes"])
        summary["delete_gate"] = _policy_delete_gate(policy)
        if summary["largest_file"]:
            summary["newest_modified_at_utc"] = _newest_mtime([summary["largest_file"]])

    for storage_class, summary in storage_summaries.items():
        summary["size_human"] = _format_bytes(summary["bytes"])
        summary["new_size_human"] = _format_bytes(summary["new_bytes"])
        summary["protected_human"] = _format_bytes(summary["protected_bytes"])
        summary["artifact_families"] = sorted(summary["artifact_families"])
        summary["delete_gate"] = delete_gate_for_storage_class(storage_class)

    largest_files.sort(key=lambda row: row["bytes"], reverse=True)
    recent_files.sort(key=lambda row: row["bytes"], reverse=True)
    largest_dirs = sorted(top_dirs.values(), key=lambda row: row["bytes"], reverse=True)
    new_dirs = sorted(recent_dirs.values(), key=lambda row: row["bytes"], reverse=True)
    for rows in (largest_dirs, new_dirs):
        for row in rows:
            row["size_human"] = _format_bytes(row["bytes"])

    free_shortfall = max(0, int(min_free_bytes) - int(usage.free))
    status = "PASS"
    if free_shortfall:
        status = "BLOCK"
    return {
        "schema_version": SCHEMA_VERSION,
        "generated_at_utc": generated_at.isoformat(),
        "status": status,
        "root": str(root),
        "root_exists": root.exists(),
        "lookback_hours": float(lookback_hours),
        "min_free_bytes": int(min_free_bytes),
        "disk": {
            "total_bytes": int(usage.total),
            "used_bytes": int(usage.used),
            "free_bytes": int(usage.free),
            "free_human": _format_bytes(usage.free),
            "free_shortfall_bytes": int(free_shortfall),
            "free_shortfall_human": _format_bytes(free_shortfall),
        },
        "event_day_manifests": event_day_manifests,
        "summary": {
            "file_count": file_count,
            "total_bytes": total_bytes,
            "total_human": _format_bytes(total_bytes),
            "policy_count": len(summaries),
            "storage_class_count": len(storage_summaries),
            "review_required_class_count": sum(
                1
                for row in summaries.values()
                if (row.get("delete_gate") or {}).get("status") == "REVIEW_REQUIRED"
                and row.get("bytes", 0) > 0
            ),
            "recent_file_count": len(recent_files),
            "recent_bytes": sum(row["bytes"] for row in recent_files),
            "recent_human": _format_bytes(sum(row["bytes"] for row in recent_files)),
        },
        "storage_class_contracts": storage_class_contracts_payload(),
        "storage_class_summaries": sorted(storage_summaries.values(), key=lambda row: row["bytes"], reverse=True),
        "policies": [asdict(policy) for policy in POLICIES],
        "policy_summaries": sorted(summaries.values(), key=lambda row: row["bytes"], reverse=True),
        "largest_directories": largest_dirs[: int(top_n)],
        "recent_directories": new_dirs[: int(top_n)],
        "largest_files": largest_files[: int(top_n)],
        "recent_files": recent_files[: int(top_n)],
    }


def render_report(payload: dict[str, Any]) -> str:
    summary = payload.get("summary") or {}
    disk = payload.get("disk") or {}
    lines = [
        "# Data Retention Inventory",
        "",
        f"Generated: {payload.get('generated_at_utc')}",
        f"Status: **{payload.get('status')}**",
        f"Root: `{payload.get('root')}`",
        "",
        "## Summary",
        "",
        *markdown_table(
            ["Field", "Value"],
            [
                ["Files scanned", summary.get("file_count")],
                ["Total size", summary.get("total_human")],
                ["Recent growth window", f"{payload.get('lookback_hours')} hours"],
                ["Recent bytes", summary.get("recent_human")],
                ["Free space", disk.get("free_human")],
                ["Free-space shortfall", disk.get("free_shortfall_human")],
                ["Review-required classes", summary.get("review_required_class_count")],
                ["Event-day manifests", (payload.get("event_day_manifests") or {}).get("manifest_count")],
                ["Blocked event-day manifests", (payload.get("event_day_manifests") or {}).get("block_count")],
            ],
        ),
        "",
        "## Storage Class Summary",
        "",
        *markdown_table(
            [
                "Storage Class",
                "Files",
                "Size",
                "New bytes",
                "Protected bytes",
                "Delete gate",
                "Delete permission",
                "Artifact families",
            ],
            [
                [
                    row.get("storage_class"),
                    row.get("file_count"),
                    row.get("size_human"),
                    row.get("new_size_human"),
                    row.get("protected_human"),
                    (row.get("delete_gate") or {}).get("status"),
                    (row.get("delete_gate") or {}).get("delete_permission"),
                    ", ".join((row.get("artifact_families") or [])[:6]),
                ]
                for row in payload.get("storage_class_summaries") or []
            ],
        ),
        "",
        "## Ownership And Retention",
        "",
        *markdown_table(
            ["Class", "Owner", "Files", "Size", "New bytes", "Delete gate", "Delete permission"],
            [
                [
                    row.get("policy"),
                    row.get("owner"),
                    row.get("file_count"),
                    row.get("size_human"),
                    row.get("new_size_human"),
                    (row.get("delete_gate") or {}).get("status"),
                    (row.get("delete_gate") or {}).get("delete_permission"),
                ]
                for row in payload.get("policy_summaries") or []
            ],
        ),
        "",
        "## Largest Directories",
        "",
        *markdown_table(
            ["Directory", "Files", "Size"],
            [[row.get("path"), row.get("file_count"), row.get("size_human")] for row in payload.get("largest_directories") or []],
        ),
        "",
        "## Recent Growth",
        "",
        *markdown_table(
            ["Directory", "Files", "Size"],
            [[row.get("path"), row.get("file_count"), row.get("size_human")] for row in payload.get("recent_directories") or []],
        ),
        "",
        "## Largest Files",
        "",
        *markdown_table(
            ["Path", "Policy", "Storage Class", "Artifact Family", "Size", "Modified"],
            [
                [
                    row.get("path"),
                    row.get("policy"),
                    row.get("storage_class"),
                    row.get("artifact_family"),
                    row.get("size_human"),
                    row.get("modified_at_utc"),
                ]
                for row in payload.get("largest_files") or []
            ],
        ),
        "",
        "## Operator Procedure",
        "",
        "Use the generated class table to pick the owning procedure, then create a reviewed cleanup manifest before removing local files. Prefer tiering or externalization for large historical JSONL/CSV evidence.",
        "",
    ]
    return "\n".join(lines)


def write_json(path: str | Path, payload: dict[str, Any]) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def write_report(path: str | Path, payload: dict[str, Any]) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_report(payload), encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Inventory data ownership, retention policy, and disk growth.")
    parser.add_argument("--root", default=str(DEFAULT_DATA_ROOT))
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    parser.add_argument("--report", default=str(DEFAULT_REPORT))
    parser.add_argument("--min-free-bytes", type=int, default=DEFAULT_MIN_FREE_BYTES)
    parser.add_argument("--lookback-hours", type=float, default=DEFAULT_LOOKBACK_HOURS)
    parser.add_argument("--top-n", type=int, default=DEFAULT_TOP_N)
    args = parser.parse_args(argv)
    payload = build_payload(
        args.root,
        min_free_bytes=args.min_free_bytes,
        lookback_hours=args.lookback_hours,
        top_n=args.top_n,
    )
    out = write_json(args.out, payload)
    report = write_report(args.report, payload)
    print(f"Data retention inventory: {payload['status']}")
    print(f"JSON written to {out}")
    print(f"Report written to {report}")
    return 0 if payload["status"] in {"PASS", "WARN"} else 2


if __name__ == "__main__":
    raise SystemExit(main())
