"""Daily refresh step adapters and compatibility exports."""

from __future__ import annotations

from weather.operations.daily_refresh_registry import (
    STEP_ORDER,
    carried_forward_steps,
    filter_runners_for_resume,
    planned_steps,
)
from weather.operations.daily_refresh_settled_day import (
    SETTLED_DAY_ANALYSIS_DEPENDENCIES,
    SettledDayAnalysisBarrierError,
    build_settled_day_analysis_barrier,
    parse_date_arg,
    run_settled_day_analysis_barrier_step,
    settled_analysis_target_date,
)
from weather.operations.daily_refresh_status import (
    build_rollup_freshness_status,
    pipeline_summary,
    run_step,
    variant_learning_gate_from_steps,
)
from weather.operations.daily_refresh_source_steps import (
    ingest_quality_gate_status,
    render_ingest_quality_report,
    run_event_metadata_validation_step,
    run_ingest_quality_gate_step,
    run_market_day_labels_finalize,
    run_public_wu_settlement_restore_step,
    run_reanalysis_recent_refresh_step,
    summarize_labels,
    write_ingest_quality_report,
)
from weather.operations.daily_refresh_trading_steps import (
    run_clob_order_book_tiering_step,
    run_closed_day_parquet_incremental_step,
    run_exchange_economics_rule_drift_step,
    run_maker_paper_score_step,
    run_replay_status_backfill_step,
    run_settlement_source_audit_step,
    run_taker_edge_permission_map_step,
    run_taker_finalization_watchdog_step,
    run_taker_tail_casebook_step,
    run_trading_evidence_step,
)
from weather.operations.daily_refresh_reporting_steps import (
    casebook_args,
    promotion_args,
    run_active_variant_shadow_step,
    run_daily_flow_analysis_step,
    run_daily_learning_step,
    run_daily_roll_log_hygiene_step,
    run_data_layer_audit_step,
    run_data_retention_inventory_step,
    run_disagreement_casebook_step,
    run_distribution_stage_attribution_step,
    run_fleet_observability_step,
    run_frozen_baseline_replay_trend_step,
    run_hourly_model_performance_step,
    run_june23_location_bias_repair_step,
    run_market_beating_objective_scoreboard_step,
    run_model_market_disagreement_rehydration_step,
    run_model_variant_evidence_growth_step,
    run_nightly_health_checks_step,
    run_price_free_model_learning_step,
    run_progress_audit_step,
    run_promotion_refresh_step,
    run_proper_scoring_reliability_scorecard_step,
    run_runtime_identity_reconciliation_step,
    run_settled_day_root_cause_step,
    run_shadow_ab_monitor_step,
    run_snapshot_evaluation_step,
    run_ten_minute_model_performance_step,
    run_winner_rank_parity_step,
    scoring_liveness_fields,
    write_daily_progress_ledger,
)


DEFAULT_RUNNERS = (
    ("reanalysis_recent_refresh", run_reanalysis_recent_refresh_step),
    ("ingest_quality_gate", run_ingest_quality_gate_step),
    ("event_metadata_validation", run_event_metadata_validation_step),
    ("public_wu_settlement_restore", run_public_wu_settlement_restore_step),
    ("market_day_labels_finalize", run_market_day_labels_finalize),
    ("exchange_economics_rule_drift", run_exchange_economics_rule_drift_step),
    ("taker_finalization_watchdog", run_taker_finalization_watchdog_step),
    ("taker_edge_permission_map", run_taker_edge_permission_map_step),
    ("taker_tail_casebook", run_taker_tail_casebook_step),
    ("maker_paper_score", run_maker_paper_score_step),
    ("settlement_source_audit", run_settlement_source_audit_step),
    ("trading_evidence", run_trading_evidence_step),
    ("clob_order_book_tiering", run_clob_order_book_tiering_step),
    ("replay_status_backfill", run_replay_status_backfill_step),
    ("closed_day_parquet_incremental", run_closed_day_parquet_incremental_step),
    ("hourly_model_performance", run_hourly_model_performance_step),
    ("ten_minute_model_performance", run_ten_minute_model_performance_step),
    ("price_free_model_learning", run_price_free_model_learning_step),
    ("model_market_disagreement_rehydration", run_model_market_disagreement_rehydration_step),
    ("settled_day_analysis_barrier", run_settled_day_analysis_barrier_step),
    ("runtime_identity_reconciliation", run_runtime_identity_reconciliation_step),
    ("fleet_observability", run_fleet_observability_step),
    ("promotion_refresh", run_promotion_refresh_step),
    ("shadow_ab_monitor", run_shadow_ab_monitor_step),
    ("active_variant_shadow", run_active_variant_shadow_step),
    ("proper_scoring_reliability_scorecard", run_proper_scoring_reliability_scorecard_step),
    ("frozen_baseline_replay_trend", run_frozen_baseline_replay_trend_step),
    ("model_variant_evidence_growth", run_model_variant_evidence_growth_step),
    ("progress_audit", run_progress_audit_step),
    ("disagreement_casebook", run_disagreement_casebook_step),
    ("daily_roll_log_hygiene", run_daily_roll_log_hygiene_step),
    ("nightly_health_checks", run_nightly_health_checks_step),
    ("data_layer_audit", run_data_layer_audit_step),
    ("snapshot_evaluation", run_snapshot_evaluation_step),
    ("distribution_stage_attribution", run_distribution_stage_attribution_step),
    ("settled_day_root_cause", run_settled_day_root_cause_step),
    ("winner_rank_parity", run_winner_rank_parity_step),
    ("june23_location_bias_repair", run_june23_location_bias_repair_step),
    ("data_retention_inventory", run_data_retention_inventory_step),
    ("daily_learning", run_daily_learning_step),
    ("market_beating_objective_scoreboard", run_market_beating_objective_scoreboard_step),
    ("daily_flow_analysis", run_daily_flow_analysis_step),
)
