"""Static schema records for bounded offline research artifacts."""

from __future__ import annotations

from weather.schema_registry_types import SchemaSpec


RESEARCH_REGISTERED_SCHEMAS = (
    SchemaSpec(
        "source_family_ablation_research",
        "source_family_ablation_v0.2",
        "weather.backtesting.replay_ablation",
        "active",
        "Research-unbound source-family terminal-removal replay with exact pinned-record selection, sealed support accounting, paired Brier/log-loss inference, and no serving authorization.",
    ),
    SchemaSpec(
        "workstation_source_ablation_preregistration",
        "workstation_source_ablation_preregistration_v0.3",
        "weather.reporting.research.source_ablation_hardened",
        "active",
        "Terminal non-blind source-ablation design seal with exact treatments, support, inference mechanics, market identity, and execution requirements.",
    ),
    SchemaSpec(
        "captured_source_variant_support_audit",
        "captured_source_variant_support_audit_v0.4",
        "weather.reporting.research.source_ablation_hardened",
        "active",
        "Pre-outcome exact captured-source support seal over pinned folder/date/market/snapshot/record-hash units and deterministic duplicate selection.",
    ),
    SchemaSpec(
        "source_ablation_inference_feasibility",
        "source_ablation_inference_feasibility_v0.2",
        "weather.reporting.research.source_ablation_hardened",
        "active",
        "Outcome-independent best-case sign-test and Holm mathematical feasibility seal for the exact strict and daily-summary variant-market families.",
    ),
    SchemaSpec(
        "source_ablation_runtime_support_correction",
        "source_ablation_runtime_support_correction_v0.1",
        "weather.reporting.research.source_ablation_runtime_correction",
        "active",
        "Outcome-firewalled correction seal binding the post-filter source-support repair, predecessor seals, failed attempt, and exact 44-pair parity proof.",
    ),
    SchemaSpec(
        "source_ablation_runtime_support_parity",
        "source_ablation_runtime_support_parity_v0.1",
        "weather.reporting.research.source_ablation_runtime_correction",
        "active",
        "Exact ordered 44-pair support inventory proving corrected runtime parity with the immutable source-support seal.",
    ),
    SchemaSpec(
        "workstation_source_ablation_hardened",
        "workstation_source_ablation_hardened_v0.1",
        "weather.reporting.research.source_ablation_hardened",
        "active",
        "Strict research-unbound source-ablation execution profile binding terminal seals, full code/artifact/config/input/WU closure, and complete generation publication.",
    ),
    SchemaSpec(
        "execution_identity_manifest",
        "execution_identity_manifest_v0.1",
        "weather.execution_identity",
        "active",
        "Fail-closed research execution closure over code, artifacts, configuration, pinned inputs, runtime, imports, environment, and explicit path presence or absence.",
    ),
    SchemaSpec(
        "ordinal_smoothing_sweep",
        "ordinal_smoothing_sweep_v0.1",
        "weather.reporting.research.ordinal_smoothing_sweep",
        "active",
        "Research-only H1 smoothing sweep with predeclared tune/holdout dates, native-unit strata, paired uncertainty, and fail-closed replay safety gates.",
    ),
    SchemaSpec(
        "ordinal_smoothing_robustness",
        "ordinal_smoothing_robustness_v0.1",
        "weather.reporting.research.ordinal_smoothing_robustness",
        "active",
        "Post-hoc, no-replay H1 holdout sensitivities for pinned settlement sources and exact 12-market panels, with immutable cache provenance and primary-result parity.",
    ),
    SchemaSpec(
        "ordinal_smoothing_fresh_confirmation_audit",
        "ordinal_smoothing_fresh_confirmation_audit_v0.1",
        "weather.reporting.research.ordinal_smoothing_fresh_confirmation_audit",
        "active",
        "Read-only later-date panel, pin, settlement-source, exact replay-identity, and expanded-tune cost audit before any fixed ordinal-smoothing confirmation.",
    ),
    SchemaSpec(
        "ordinal_smoothing_physical_refinement",
        "ordinal_smoothing_physical_refinement_v0.1",
        "weather.reporting.research.ordinal_smoothing_physical_refinement",
        "active",
        "Tune-only cache-derived family-aware ordinal-smoothing bandwidth refinement using preregistered physical-C anchors and an exact W0-to-W1 parity gate.",
    ),
    SchemaSpec(
        "ordinal_smoothing_physical_replay",
        "ordinal_smoothing_physical_replay_v0.1",
        "weather.reporting.research.ordinal_smoothing_physical_replay",
        "active",
        "Research-only five-arm tune replay with per-family physical bandwidth mapping, compact caches, W0 determinism, and no holdout or serving mutation.",
    ),
    SchemaSpec(
        "ordinal_smoothing_literal_panel",
        "ordinal_smoothing_literal_panel_v0.1",
        "weather.reporting.research.ordinal_smoothing_panel_materializer",
        "active",
        "Outcome-firewalled exact-date promotion-corpus derivative for cold H1 tune and one-shot confirmation runners.",
    ),
    SchemaSpec(
        "ordinal_smoothing_physical_replay_gen2",
        "ordinal_smoothing_physical_replay_gen2_v0.1",
        "weather.reporting.research.ordinal_smoothing_physical_replay_gen2",
        "active",
        "Research-unbound generation-2 physical smoothing replay with exact execution closure, immutable design binding, and exclusive generation publication.",
    ),
    SchemaSpec(
        "ordinal_smoothing_physical_replay_gen2_profile",
        "ordinal_smoothing_physical_replay_gen2_strict_v0.1",
        "weather.reporting.research.ordinal_smoothing_physical_replay_gen2",
        "active",
        "Strict execution profile identifier for the generation-2 physical-smoothing replay.",
    ),
    SchemaSpec(
        "ordinal_smoothing_physical_replay_gen2_generation_commit",
        "ordinal_smoothing_physical_replay_gen2_generation_commit_v0.1",
        "weather.reporting.research.ordinal_smoothing_physical_replay_gen2",
        "active",
        "Exclusive final commit marker for one complete generation-2 physical-smoothing replay generation.",
    ),
    SchemaSpec(
        "ordinal_smoothing_physical_confirmation",
        "ordinal_smoothing_physical_confirmation_v0.1",
        "weather.reporting.research.ordinal_smoothing_physical_confirmation",
        "active",
        "Cold fixed-arm ordinal-smoothing confirmation over the sealed later-date panel, kept research-unbound and decision-gated.",
    ),
    SchemaSpec(
        "ordinal_smoothing_physical_confirmation_profile",
        "ordinal_smoothing_physical_confirmation_strict_v0.1",
        "weather.reporting.research.ordinal_smoothing_physical_confirmation",
        "active",
        "Strict one-shot execution profile identifier for physical-smoothing confirmation.",
    ),
    SchemaSpec(
        "ordinal_smoothing_physical_confirmation_generation_commit",
        "ordinal_smoothing_physical_confirmation_generation_commit_v0.1",
        "weather.reporting.research.ordinal_smoothing_physical_confirmation",
        "active",
        "Exclusive final commit marker for one complete cold ordinal-smoothing confirmation generation.",
    ),
    SchemaSpec(
        "workstation_morning_frontier",
        "workstation_morning_frontier_v0.2",
        "weather.reporting.research.workstation_morning_frontier",
        "active",
        "Research-only fleet-date morning forecast frontier with retrospective tune-only 09:00 city selection, separately reported holdout evaluation, and joint Holm correction across city-level Brier/log-loss tests.",
    ),
    SchemaSpec(
        "workstation_taker_bakeoff",
        "workstation_taker_bakeoff_v0.1",
        "weather.reporting.research.workstation_taker_bakeoff",
        "active",
        "Frozen-input workstation taker replay with bounded market-day and paired fleet-date evidence.",
    ),
    SchemaSpec(
        "workstation_current_replay_time_frontier",
        "workstation_current_replay_time_frontier_v0.1",
        "weather.reporting.research.current_replay_time_frontier",
        "active",
        "Memory-bounded current-replay hourly frontier for tune-selected H1 arms with market-date and fleet-date equal weighting.",
    ),
    SchemaSpec(
        "offline_tmax_predictor_evaluation",
        "offline_tmax_predictor_evaluation_v0.1",
        "weather.reporting.research.offline_tmax_predictor_evaluation",
        "active",
        "Leakage-safe one-family Tmax predictor evaluation with blocked chronological validation and fleet-date clustered uncertainty.",
    ),
    SchemaSpec(
        "radiation_previous_runs_research",
        "radiation_previous_runs_research_v0.1",
        "weather.reporting.research.radiation_previous_runs_research",
        "active",
        "Scratch-only fixed-lead radiation acquisition manifest for leakage-safe offline Tmax research.",
    ),
    SchemaSpec(
        "cfsv2_pressure_research",
        "cfsv2_pressure_research_v0.1",
        "weather.reporting.research.cfsv2_pressure_research",
        "active",
        "Scratch-only bounded NOAA CFSv2 850 hPa acquisition manifest with conservative availability buffering for offline Tmax research.",
    ),
    SchemaSpec(
        "cfsv2_soil_availability_contract",
        "cfsv2_soil_availability_contract_v0.1",
        "weather.reporting.research.cfsv2_soil_research",
        "active",
        "Outcome-blind complete-pair availability contract for exact NOAA CFSv2 top-layer soil fields under one fixed cycle/member rule.",
    ),
    SchemaSpec(
        "cfsv2_soil_research",
        "cfsv2_soil_research_v0.1",
        "weather.reporting.research.cfsv2_soil_research",
        "active",
        "Scratch-only bounded NOAA CFSv2 0-0.1 m soil acquisition manifest for leakage-safe offline Tmax research.",
    ),
    SchemaSpec(
        "cfsv2_radiation_design_contract",
        "cfsv2_radiation_design_contract_v0.1",
        "weather.reporting.research.cfsv2_radiation_research",
        "active",
        "Outcome-blind exact-field, arithmetic, support, split, and acceptance contract for a NOAA CFSv2 radiation source-contract sensitivity.",
    ),
    SchemaSpec(
        "cfsv2_radiation_research",
        "cfsv2_radiation_research_v0.1",
        "weather.reporting.research.cfsv2_radiation_research",
        "active",
        "Scratch-only bounded NOAA CFSv2 total/diffuse/direct-derived/cloud radiation manifest for leakage-safe offline Tmax research.",
    ),
    SchemaSpec(
        "hrrr_smoke_design_contract",
        "hrrr_smoke_design_contract_v0.1",
        "weather.reporting.research.hrrr_smoke_research",
        "active",
        "Outcome-blind HRRR AOTK/smoke issue-time, field, unit-boundary, transform, grid, split, and acceptance contract.",
    ),
    SchemaSpec(
        "hrrr_smoke_research",
        "hrrr_smoke_research_v0.1",
        "weather.reporting.research.hrrr_smoke_research",
        "active",
        "Scratch-only bounded NOAA HRRR AOTK and normalized smoke-mass acquisition manifest for leakage-safe offline Tmax research.",
    ),
    SchemaSpec(
        "offline_tmax_bootstrap_sensitivity",
        "offline_tmax_bootstrap_sensitivity_v0.1",
        "weather.reporting.research.offline_tmax_predictor_evaluation",
        "active",
        "Deterministic higher-replicate clustered-bootstrap sensitivity computed from sealed offline Tmax holdout error summaries without refitting.",
    ),
    SchemaSpec(
        "offline_tmax_methodology_sensitivity",
        "offline_tmax_methodology_sensitivity_v0.1",
        "weather.reporting.research.offline_tmax_methodology_sensitivity",
        "active",
        "No-refit equal-fleet-date and exact-complete-fleet sensitivity computed from sealed offline Tmax holdout error summaries.",
    ),
    SchemaSpec(
        "offline_tmax_multiplicity_audit",
        "offline_tmax_multiplicity_audit_v0.1",
        "weather.reporting.research.offline_tmax_multiplicity_audit",
        "active",
        "Program-level two-sided fleet-date clustered primary-MAE evidence with Holm family-wise adjustment across sealed Tmax predictor families.",
    ),
    SchemaSpec(
        "workstation_maker_research",
        "workstation_maker_research_v0.1",
        "weather.reporting.research.workstation_maker_research",
        "active",
        "Research-only maker reconstruction using explicit last-trade events, locked tune/holdout comparisons, and separated theoretical incentives.",
    ),
    SchemaSpec(
        "pool_city_training_benchmark",
        "pool_city_training_benchmark_v0.1",
        "weather.reporting.research.pool_city_training_benchmark",
        "active",
        "Leakage-safe pooled, per-city, and leave-one-city-out continuous-density training benchmark with native-unit scoring and fleet-date clustered uncertainty.",
    ),
    SchemaSpec(
        "balanced_market_date_hour_panel",
        "balanced_market_date_hour_panel_v1",
        "weather.reporting.research.pool_city_training_benchmark",
        "active",
        "Balanced market/date/hour corpus contract for pooled, per-city, and leave-one-city-out density research.",
    ),
    SchemaSpec(
        "pool_city_checkpoint_status",
        "pool_city_checkpoint_status_v0.2",
        "weather.reporting.research.pool_city_training_benchmark",
        "active",
        "Self-authenticating resumable task-progress ledger bound to the exact pool-versus-city run and task inventory.",
        supersedes=("pool_city_checkpoint_status_v0.1",),
        migration_notes="Legacy unauthenticated status ledgers are intentionally rejected and tasks must be recomputed under the sealed v0.2 run contract.",
    ),
    SchemaSpec(
        "pool_city_checkpoint_status_legacy",
        "pool_city_checkpoint_status_v0.1",
        "weather.reporting.research.pool_city_training_benchmark",
        "retired",
        "Legacy unauthenticated task-progress ledger retained only for explicit rejection and historical interpretation.",
    ),
    SchemaSpec(
        "pool_city_task_checkpoint",
        "pool_city_task_checkpoint_v0.2",
        "weather.reporting.research.pool_city_training_benchmark",
        "active",
        "Self-authenticating research task checkpoint bound to the exact code/config, Git, corpus, manifest, feature, grid, run, task, and prediction-key contracts.",
    ),
    SchemaSpec(
        "pool_city_execution_source_closure",
        "pool_city_execution_source_closure_v0.2",
        "weather.reporting.research.pool_city_training_benchmark",
        "active",
        "Deterministic over-complete repository code, configuration, Git, callable-owner, and runtime dependency closure for pool-versus-city research.",
    ),
    SchemaSpec(
        "pool_city_checkpoint_run_contract",
        "pool_city_checkpoint_run_contract_v0.2",
        "weather.reporting.research.pool_city_training_benchmark",
        "active",
        "Shared exact execution closure binding every authenticated pool-versus-city task checkpoint.",
    ),
    SchemaSpec(
        "pool_city_task_contract",
        "pool_city_task_contract_v0.2",
        "weather.reporting.research.pool_city_training_benchmark",
        "active",
        "Per-task feature, scope, and exact prediction-key closure for pool-versus-city checkpoint validation.",
    ),
    SchemaSpec(
        "pool_city_input_manifest",
        "pool_city_input_manifest_v0.1",
        "weather.reporting.research.pool_city_training_benchmark",
        "active",
        "Exact read-only input-file provenance manifest for the pool-versus-city density benchmark.",
    ),
    SchemaSpec(
        "pool_city_read_only_guard_contract",
        "python_open_and_common_pathname_mutation_v0.2",
        "weather.reporting.research.pool_city_training_benchmark",
        "active",
        "Python-level read and common pathname-mutation guard contract applied while the pool-versus-city corpus is loaded from the mirrored data root.",
    ),
    SchemaSpec(
        "pool_city_runtime_plan",
        "pool_city_runtime_plan_v0.1",
        "weather.reporting.research.pool_city_training_benchmark",
        "active",
        "Measured pilot runtime and resource plan for the pool-versus-city density benchmark.",
    ),
    SchemaSpec(
        "source_ablation_synthesis",
        "source_ablation_synthesis_v0.2",
        "weather.reporting.research.source_ablation_synthesis",
        "active",
        "Non-blind same-corpus 22-treatment synthesis bound to immutable design, support, feasibility, execution-closure, strict-panel, and Holm-corrected daily-summary city evidence.",
    ),
    SchemaSpec(
        "source_ablation_synthesis_profile",
        "source_ablation_synthesis_hardened_v0.1",
        "weather.reporting.research.source_ablation_synthesis_hardened",
        "active",
        "Strict execution profile identifier for sealed source-ablation synthesis.",
    ),
    SchemaSpec(
        "source_ablation_synthesis_generation_commit",
        "source_ablation_synthesis_generation_commit_v0.1",
        "weather.reporting.research.source_ablation_synthesis_hardened",
        "active",
        "Exclusive final commit marker for one sealed source-ablation synthesis generation, binding both output hashes, terminal source receipts, and synthesis execution identity.",
    ),
    SchemaSpec(
        "source_ablation_generation_commit",
        "source_ablation_generation_commit_v0.1",
        "weather.reporting.research.source_ablation_hardened",
        "active",
        "Exclusive final commit marker for one complete hardened source-ablation generation, binding output hashes, terminal seals, and execution identity.",
    ),
    SchemaSpec(
        "source_ablation_runtime_support_audit",
        "source_ablation_runtime_support_audit_v0.1",
        "weather.backtesting.replay_ablation",
        "active",
        "Exact runtime recomputation of sealed source-ablation snapshot and market-day support units, with all supported snapshots required to score.",
    ),
)
