"""Recent static schema records for the schema registry."""

from __future__ import annotations

from weather.schema_registry_types import SchemaSpec


RECENT_REGISTERED_SCHEMAS = (
    SchemaSpec(
        "pit_forecast_normalizer",
        "open_meteo_previous_runs_pit_v1",
        "weather.sources.forecast_training_corpus",
        "active",
        "Normalizer contract for issue-preserving Open-Meteo Previous Runs responses.",
    ),
    SchemaSpec(
        "pit_forecast_corpus_plan",
        "pit_forecast_corpus_plan_v1",
        "weather.sources.forecast_training_corpus",
        "active",
        "Immutable, network-free request plan for the training-only point-in-time forecast corpus.",
    ),
    SchemaSpec(
        "pit_forecast_staged_response",
        "pit_forecast_staged_response_v1",
        "weather.sources.forecast_training_corpus",
        "active",
        "Request-keyed raw-response receipt with HTTP metadata, hashes, validation, and issue evidence.",
    ),
    SchemaSpec(
        "pit_forecast_failure",
        "pit_forecast_failure_v1",
        "weather.sources.forecast_training_corpus",
        "active",
        "Append-only failure-ledger row for staging and materialization blocks.",
    ),
    SchemaSpec(
        "pit_forecast_corpus_row",
        "pit_forecast_corpus_row_v1",
        "weather.sources.forecast_training_corpus",
        "active",
        "Cutoff-safe training-only forecast daily and hourly rows with raw-response lineage.",
    ),
    SchemaSpec(
        "pit_forecast_corpus_coverage",
        "pit_forecast_corpus_coverage_v1",
        "weather.sources.forecast_training_corpus",
        "active",
        "Per-market/year/date/field/issue/cutoff coverage decision for the PIT forecast corpus.",
    ),
    SchemaSpec(
        "pit_forecast_corpus_manifest",
        "pit_forecast_corpus_manifest_v1",
        "weather.sources.forecast_training_corpus",
        "active",
        "Content-addressed immutable manifest for a complete training-only PIT forecast corpus.",
    ),
    SchemaSpec(
        "pit_forecast_training_preflight",
        "pit_forecast_training_preflight_v1",
        "weather.calibration.forecast_training_contract",
        "active",
        "Self-hashed fail-closed preflight binding a retrain to an explicit PIT forecast corpus.",
    ),
    SchemaSpec(
        "forecast_payload_manifest",
        "forecast_payload_manifest_v2",
        "weather.collection.snapshot_store",
        "active",
        "Shared/local content-addressed forecast payload references, byte observability, and point-in-time extraction provenance.",
        supersedes=("forecast_payload_manifest_v1",),
        migration_notes="Legacy market-local v1 manifests remain immutable and replayable; new explicitly market-invariant responses use the shared CAS.",
    ),
    SchemaSpec(
        "forecast_payload_extraction_identity_nbm_nbp",
        "nbm_nbp_station_target_v1",
        "weather.forecast_payload_contracts",
        "active",
        "Replay-complete NBM national bulletin extraction identity containing station and target date.",
    ),
    SchemaSpec(
        "forecast_payload_cas_migration_dry_run",
        "forecast_payload_cas_migration_dry_run_v0.1",
        "weather.operations.forecast_payload_cas_migration",
        "active",
        "Inventory-only legacy NBM migration/replay and partial snapshot-manifest shared-reference verification with deletion disabled.",
    ),
    SchemaSpec(
        "forecast_payload_cas_migration_dry_run",
        "forecast_payload_cas_migration_dry_run_v0.2",
        "weather.operations.forecast_payload_cas_migration",
        "active",
        "Bounded, resumable inventory-only legacy NBM migration scan with month selection, streaming totals, explicit scan bounds, and deletion disabled.",
        supersedes=("forecast_payload_cas_migration_dry_run_v0.1",),
        migration_notes="v0.2 adds month selection, per-bound partial results, and physical-blob dedup counting; v0.1 reports remain readable.",
    ),
    SchemaSpec(
        "forecast_payload_cross_process_fanout_receipt",
        "forecast_payload_cross_process_fanout_receipt_v0.1",
        "weather.collection.forecast_payload_fetch_fanout",
        "active",
        "Cross-process single-fetch claim/receipt under the shared CAS: one isolated child fetches the NBM payload, followers verify receipt identity and CAS hash/size with bounded wait and fail-open.",
    ),
    SchemaSpec(
        "forecast_payload_storage_observability",
        "forecast_payload_storage_observability_v0.1",
        "weather.collection.forecast_payload_cas",
        "active",
        "Per-capture created/reused blob counts and logical, physical, avoided-byte budget evidence.",
    ),
    SchemaSpec(
        "runtime_monitor_run",
        "runtime_monitor_v0.1",
        "weather.operations.runtime_monitor",
        "active",
        "Bounded host/runtime monitor run manifest and resumable state.",
    ),
    SchemaSpec(
        "runtime_monitor_component",
        "runtime_monitor_component_v0.1",
        "weather.operations.runtime_monitor",
        "active",
        "Bounded health projection for one monitored runtime component.",
    ),
    SchemaSpec(
        "runtime_monitor_host",
        "runtime_monitor_host_v0.1",
        "weather.operations.runtime_monitor",
        "active",
        "Bounded host CPU, memory, disk, process, and task resource sample.",
    ),
    SchemaSpec(
        "runtime_monitor_event",
        "runtime_monitor_event_v0.1",
        "weather.operations.runtime_monitor",
        "active",
        "New component-state or incremental-log event observed during a monitor run.",
    ),
    SchemaSpec(
        "runtime_monitor_baseline",
        "runtime_monitor_baseline_v0.1",
        "weather.operations.runtime_monitor",
        "active",
        "Short initial resource baseline used to contextualize the longer soak.",
    ),
    SchemaSpec(
        "runtime_monitor_summary",
        "runtime_monitor_summary_v0.1",
        "weather.operations.runtime_monitor",
        "active",
        "Bounded per-bucket aggregation of runtime-monitor host samples.",
    ),
    SchemaSpec(
        "runtime_monitor_final",
        "runtime_monitor_final_v0.1",
        "weather.operations.runtime_monitor",
        "active",
        "Final bounded monitor-run health, artifact, resource, and event summary.",
    ),
    SchemaSpec(
        "served_stage_ablation_predictor_config",
        "served_stage_ablation_predictor_config_v1",
        "weather.calibration.served_stage_ablation",
        "active",
        "Hash-bound runtime adapter configuration for one sanitized E3/E4 experiment, embargo, seed, and safety probe call.",
    ),
    SchemaSpec(
        "legacy_pooled_postprocess_fit_contract",
        "legacy_pooled_postprocess_fit_contract_v1",
        "weather.calibration.pooled_training",
        "active",
        "Identity-only fail-closed receipt proving an outer holdout was not reused to fit legacy served postprocessing.",
    ),
    SchemaSpec(
        "pooled_band_point_in_time_training",
        "pooled_band_point_in_time_training_v1",
        "weather.calibration.pooled_training",
        "active",
        "Preselection-bound nested pooled-band training plan and output-bound six-stage fit receipt graph.",
    ),
    SchemaSpec(
        "pooled_band_final_refit_receipt",
        "pooled_band_final_refit_receipt_v1",
        "weather.calibration.pooled_training",
        "active",
        "Self-hashed proof binding the final pooled HGB refit to unlocked inputs and serialized model payloads.",
    ),
    SchemaSpec(
        "pooled_nested_postprocess_fit_contract",
        "pooled_nested_postprocess_fit_contract_v1",
        "weather.calibration.pooled_training",
        "active",
        "Identity learned-postprocess contract backed by real nested training-only receipts.",
    ),
    SchemaSpec(
        "served_calibration_stage_ablation",
        "served_calibration_stage_ablation_v1",
        "weather.model_stage_retirement",
        "active",
        "Paired whole-date identity-versus-literal-served calibration ablation used by the retirement gate.",
    ),
    SchemaSpec(
        "weather_model_stage_retirement_register",
        "weather_model_stage_retirement_register_v1",
        "weather.model_stage_retirement",
        "active",
        "Self-hashed retain, quarantine, or retire disposition for incumbent and residual serving stages.",
    ),
    SchemaSpec(
        "residual_distribution_stress_evaluation",
        "residual_distribution_stress_evaluation_v1",
        "weather.calibration.residual_distribution_stress",
        "active",
        "Self-hashed leakage, fault, cadence, metamorphic, settlement-uncertainty, and rare-regime stress report for ResidualDistributionV1.",
    ),
    SchemaSpec(
        "residual_distribution_v1",
        "residual_distribution_v1_v0.1",
        "weather.model.residual_distribution_v1",
        "archived",
        "Initial inert ResidualDistributionV1 candidate artifact contract.",
    ),
    SchemaSpec(
        "residual_distribution_training_corpus",
        "residual_distribution_training_corpus_v1",
        "weather.calibration.residual_distribution_corpus",
        "archived",
        "Initial replay-input residual training row contract.",
    ),
    SchemaSpec(
        "residual_distribution_training_corpus_manifest",
        "residual_distribution_training_corpus_manifest_v1",
        "weather.calibration.residual_distribution_corpus",
        "archived",
        "Initial residual training corpus manifest contract.",
    ),
    SchemaSpec(
        "residual_distribution_requalification",
        "residual_distribution_requalification_v0.1",
        "weather.calibration.residual_distribution_v1",
        "archived",
        "Initial nested residual candidate report contract.",
    ),
    SchemaSpec(
        "residual_distribution_v1_release_config",
        "residual_distribution_v1_release_config_v1",
        "weather.residual_distribution_release",
        "active",
        "Self-hashed immutable release configuration binding every ResidualDistributionV1 qualification input.",
    ),
    SchemaSpec(
        "residual_distribution_v1_forward_attestation",
        "residual_distribution_v1_forward_attestation_v1",
        "weather.residual_distribution_release",
        "active",
        "External self-hashed parity and forward-streaming attestation bound to one exact inactive ResidualDistributionV1 release manifest and artifact.",
    ),
    SchemaSpec(
        "residual_distribution_preselection_lock",
        "residual_distribution_preselection_lock_v1",
        "weather.calibration.residual_distribution_lock",
        "active",
        "Append-only self-hashed candidate, corpus, comparator, metric, and untouched-window declaration recorded before evaluation.",
    ),
    SchemaSpec(
        "residual_distribution_v1",
        "residual_distribution_v1_v0.2",
        "weather.model.residual_distribution_v1",
        "active",
        "Shadow-only pooled NWP-residual density model with explicit missingness, source health, legal settlement truncation, and one simplex calibrator.",
        supersedes=("residual_distribution_v1_v0.1",),
        migration_notes="Qualification is now evidence-finalized and degraded source states fail closed instead of becoming learned permissions.",
    ),
    SchemaSpec(
        "residual_distribution_training_corpus",
        "residual_distribution_training_corpus_v2",
        "weather.calibration.residual_distribution_corpus",
        "active",
        "Hash-linked one-row-per-market/date/cutoff training corpus materialized from captured replay inputs.",
        supersedes=("residual_distribution_training_corpus_v1",),
        migration_notes="Rows bind release/config identity and captured comparator partitions; proof-grade input families are explicit.",
    ),
    SchemaSpec(
        "residual_distribution_training_corpus_manifest",
        "residual_distribution_training_corpus_manifest_v2",
        "weather.calibration.residual_distribution_corpus",
        "active",
        "Self-hashed provenance, exclusion, and checkpoint-selection manifest for the residual distribution corpus.",
        supersedes=("residual_distribution_training_corpus_manifest_v1",),
        migration_notes="Manifest requires hashed core input families and singular release/runtime identity for qualification.",
    ),
    SchemaSpec(
        "simplex_temperature",
        "simplex_temperature_v1",
        "weather.calibration.simplex_calibration",
        "active",
        "Single global power-temperature calibrator fitted to complete out-of-fold market partitions.",
    ),
    SchemaSpec(
        "residual_distribution_requalification",
        "residual_distribution_requalification_v0.2",
        "weather.calibration.residual_distribution_v1",
        "active",
        "Nested whole-fleet-date residual-model ablation, calibration, and qualification result.",
        supersedes=("residual_distribution_requalification_v0.1",),
        migration_notes="Adds comparators, ordered metrics, clustered intervals, locked-window scoring, and external evidence finalization.",
    ),
    SchemaSpec(
        "residual_distribution_oof_fit_receipt",
        "residual_distribution_oof_fit_receipt_v0.1",
        "weather.calibration.residual_distribution_v1",
        "active",
        "Hash-linked receipt for residual scale and simplex calibration fitted only from inner out-of-fold predictions.",
    ),
    SchemaSpec(
        "residual_distribution_final_fit_receipt",
        "residual_distribution_final_fit_receipt_v0.1",
        "weather.calibration.residual_distribution_v1",
        "active",
        "Hash-linked proof that the final residual model refit excluded every locked evaluation date.",
    ),
    SchemaSpec(
        "event_day_archive_coverage_audit",
        "event_day_archive_coverage_audit_v0.2",
        "weather.operations.event_day_archive_coverage",
        "active",
        "Self-hashed bounded manifest-index audit with structural identities, cursor freshness/completeness, and exact archive/event/cursor hash linkage.",
        supersedes=("event_day_archive_coverage_audit_v0.1",),
        migration_notes="Coverage metrics distinguish declared manifests from fully linked evidence; schema-only cursor validity no longer passes.",
    ),
    SchemaSpec(
        "automatic_experiment_queue",
        "automatic_experiment_queue_v0.2",
        "weather.reporting.daily.daily_learning_scorecard",
        "active",
        "Daily experiment queue whose executable entries require a verified immutable manifest; legacy ideas remain visible and ineligible.",
        supersedes=("automatic_experiment_queue_v0.1",),
        migration_notes="Status alone no longer grants eligibility; a valid executable_experiment_manifest_v0.1 is mandatory.",
    ),
    SchemaSpec(
        "executable_experiment_manifest",
        "executable_experiment_manifest_v0.1",
        "weather.experiment_contract",
        "active",
        "Self-hashed executable experiment specification with immutable inputs, candidate-only outputs, metrics, decisions, and budgets.",
    ),
    SchemaSpec(
        "executable_experiment_result",
        "executable_experiment_result_v0.1",
        "weather.experiment_contract",
        "active",
        "Self-hashed terminal experiment outcome validated against its immutable manifest and decision rule.",
    ),
    SchemaSpec(
        "runtime_identity_evidence",
        "runtime_identity_evidence_v0.1",
        "weather.reporting.serving_gates.runtime_identity_evidence",
        "active",
        "Runtime identity reconciliation evidence over snapshot and trading artifacts.",
    ),
    SchemaSpec(
        "runtime_identity_reconciliation",
        "runtime_identity_reconciliation_v0.1",
        "weather.reporting.serving_gates.runtime_identity_reconciliation",
        "active",
        "Fail-closed reviewed reconciliation surface for mixed runtime identity aggregation.",
    ),
    SchemaSpec(
        "snapshot_core_sidecar_backfill",
        "snapshot_core_sidecar_backfill_v0.1",
        "weather.collection.snapshot_store",
        "active",
        "Snapshot core sidecar backfill report.",
    ),
    SchemaSpec(
        "snapshot_core_sidecar_backfill_batch",
        "snapshot_core_sidecar_backfill_batch_v0.1",
        "weather.collection.snapshot_store",
        "active",
        "Batch snapshot core sidecar backfill report.",
    ),
    SchemaSpec(
        "snapshot_explanation_backfill",
        "snapshot_explanation_backfill_v0.1",
        "weather.collection.snapshot_store",
        "active",
        "Snapshot explanation sidecar backfill report.",
    ),
    SchemaSpec(
        "snapshot_explanation_backfill_batch",
        "snapshot_explanation_backfill_batch_v0.1",
        "weather.collection.snapshot_store",
        "active",
        "Batch snapshot explanation sidecar backfill report.",
    ),
    SchemaSpec(
        "snapshot_explanations",
        "snapshot_explanations_v0.1",
        "weather.collection.snapshot_store",
        "active",
        "Snapshot explanation sidecar artifact.",
    ),
    SchemaSpec(
        "snapshot_sidecar_eligibility",
        "snapshot_sidecar_eligibility_v0.1",
        "weather.calibration.pooled_candidate_replay_diagnostics",
        "active",
        "Snapshot sidecar eligibility diagnostics.",
    ),
    SchemaSpec(
        "source_status_proof",
        "source_status_proof_v0.1",
        "weather.collection.collection_health",
        "active",
        "Proof artifact for source-status freshness and degradation.",
    ),
    SchemaSpec(
        "source_status_proof",
        "source_status_proof_v0.2",
        "weather.collection.collection_health",
        "active",
        "Proof artifact for source-status freshness and degradation with optional provider outages.",
        supersedes=("source_status_proof_v0.1",),
        migration_notes=(
            "Settlement-source auth failures can be covered by the free-source replacement proof."
        ),
    ),
    SchemaSpec(
        "mm_live_readiness",
        "mm_live_readiness_v0.2",
        "weather.market.market_making_readiness",
        "active",
        "Conservative market-making live-readiness summary and sorted no-go gate evidence.",
    ),
    SchemaSpec(
        "mm_quote_blocker_diagnostics",
        "mm_quote_blocker_diagnostics_v0.8",
        "weather.market.mm_paper",
        "active",
        "Market-making paper quote blocker diagnostics with known-edge and event-gate overlap evidence.",
    ),
    SchemaSpec(
        "mm_quote_intent",
        "mm_quote_intent_v0.3",
        "weather.market.mm_policy",
        "active",
        "Per-row market-making quote intent and no-quote decision schema.",
    ),
    SchemaSpec(
        "mm_execution_evidence",
        "mm_execution_evidence_v0.1",
        "weather.market.mm_paper_scoring",
        "active",
        "Normalized genuine-execution provenance embedded in admitted trades, fill-evidence diagnostics, and persisted maker-paper fill rows.",
    ),
    SchemaSpec(
        "mm_scoring_projection",
        "mm_scoring_projection_v0.1",
        "weather.market.mm_scoring_projection",
        "active",
        "Compact source-bound base and model-variant quote inputs for bounded maker-paper scoring.",
    ),
    SchemaSpec(
        "mm_reward_score_diagnostics",
        "mm_reward_score_diagnostics_v0.2",
        "weather.market.mm_paper",
        "active",
        "Market-making reward score diagnostics including reward-share and competitor-score evidence.",
    ),
    SchemaSpec(
        "taker_bot_policy",
        "taker_bot_policy_v0.1",
        "weather.market.taker_bot",
        "active",
        "Taker-bot policy/config artifact.",
    ),
    SchemaSpec(
        "taker_clustered_promotion_gate",
        "taker_clustered_promotion_gate_v0.1",
        "weather.market.taker_bot_bakeoff",
        "active",
        "Clustered promotion gate for taker strategy/model variants.",
    ),
    SchemaSpec(
        "taker_counterfactual_tape",
        "taker_counterfactual_tape_v0.1",
        "weather.market.taker_bot_tape_io",
        "active",
        "Counterfactual taker order tape.",
    ),
    SchemaSpec(
        "taker_incremental_state",
        "taker_incremental_state_v0.1",
        "weather.market.taker_bot_incremental",
        "active",
        "SQLite intent index and restart checkpoint for append-only taker tapes.",
    ),
    SchemaSpec(
        "taker_incremental_persistence",
        "taker_incremental_persistence_v0.1",
        "weather.market.taker_bot_incremental",
        "active",
        "Per-tick evidence describing append/checkpoint taker persistence and bounded materialization.",
    ),
    SchemaSpec(
        "taker_incremental_pnl",
        "taker_incremental_pnl_v0.1",
        "weather.market.taker_bot_incremental",
        "active",
        "Cumulative taker PnL assembled from bounded fills and incremental counters.",
    ),
    SchemaSpec(
        "taker_pending_tick",
        "taker_pending_tick_v0.1",
        "weather.market.taker_bot_cli",
        "active",
        "Durable staged taker tick outbox used for exact crash recovery across append phases.",
    ),
    SchemaSpec(
        "taker_resource_budgets",
        "taker_resource_budgets_v0.1",
        "weather.market.taker_bot_incremental",
        "active",
        "Declared taker tick memory, tape-I/O, duration, and post-warmup slope budgets.",
    ),
    SchemaSpec(
        "taker_tick_resource_diagnostics",
        "taker_tick_resource_diagnostics_v0.1",
        "weather.market.taker_bot_incremental",
        "active",
        "Advisory taker tick resource measurements and budget checks.",
    ),
    SchemaSpec(
        "taker_edge_permission_map",
        "taker_edge_permission_map_v0.1",
        "weather.market.taker_edge_permission",
        "active",
        "Per-slice taker edge permission map.",
    ),
    SchemaSpec(
        "taker_model_variant_shadow_bakeoff",
        "taker_model_variant_shadow_bakeoff_v0.1",
        "weather.market.taker_bot_bakeoff",
        "active",
        "Taker model-variant shadow bakeoff report.",
    ),
    SchemaSpec(
        "taker_strategy_bakeoff_ledger_projection",
        "taker_strategy_bakeoff_ledger_projection_v0.1",
        "weather.market.taker_bot_artifact_projection",
        "active",
        "Compact content-bound bakeoff fields for finalization and champion/challenger readers.",
    ),
    SchemaSpec(
        "taker_settled_finalization_projection",
        "taker_settled_finalization_projection_v0.1",
        "weather.market.taker_bot_artifact_projection",
        "active",
        "Compact source-bound finalization state for bounded freshness and profitability checks.",
    ),
    SchemaSpec(
        "taker_profitability_artifact_verification_v0_2",
        "taker_profitability_artifact_verification_v0.2",
        "weather.market.taker_bot_bakeoff",
        "deprecated",
        "Deprecated lookup alias for taker_profitability_artifact_verification_composite.",
        supersedes=("taker_profitability_artifact_verification_v0.1",),
    ),
    SchemaSpec(
        "promotion_heavy_diagnostics",
        "promotion_heavy_diagnostics_v0.1",
        "weather.calibration.pooled_candidate_replay",
        "active",
        "Reusable heavy-diagnostics manifest keyed by candidate artifact lineage.",
    ),
    SchemaSpec(
        "serving_gauntlet_manifest",
        "serving_gauntlet_manifest_v0.1",
        "weather.reporting.promotion.orchestration",
        "active",
        "Reusable serving-gauntlet summary keyed by serving artifact lineage.",
    ),
    SchemaSpec(
        "unfenced_taker_bakeoff_sweep",
        "unfenced_taker_bakeoff_sweep_v0.1",
        "weather.reporting.research.unfenced_taker_bakeoff_sweep",
        "active",
        "Counterfactual research sweep with the taker permission fence disabled.",
    ),
    SchemaSpec(
        "release_manifest",
        "release_manifest_v0.1",
        "weather.operations.release_manifest",
        "active",
        "Immutable model release artifact, runtime, routing, configuration, and lineage inventory.",
    ),
    SchemaSpec(
        "first_inactive_release_bootstrap",
        "first_inactive_release_bootstrap_v0.1",
        "weather.operations.release_bootstrap",
        "active",
        "Self-hashed fail-closed authorization and qualification receipt for constructing the first inactive production release without pre-existing release-bound parity.",
    ),
    SchemaSpec(
        "active_release_pointer",
        "active_release_pointer_v0.1",
        "weather.operations.release_promotion",
        "active",
        "Atomic active-release pointer with a verified rollback target.",
    ),
    SchemaSpec(
        "release_promotion_decision",
        "release_promotion_decision_v0.1",
        "weather.operations.release_promotion",
        "active",
        "Reviewed fail-closed decision proof authorizing one release promotion.",
    ),
    SchemaSpec(
        "release_market_day_boundary",
        "release_market_day_boundary_v0.1",
        "weather.operations.release_promotion",
        "active",
        "Fresh quiescence proof authorizing a release change at a market-day boundary.",
    ),
    SchemaSpec(
        "release_rollback_drill",
        "release_rollback_drill_v0.1",
        "weather.operations.release_promotion",
        "active",
        "Hash-linked rollback, coordinated restart, restored identity, and health drill proof.",
    ),
    SchemaSpec(
        "inactive_release_forward_shadow",
        "inactive_release_forward_shadow_v0.1",
        "weather.reporting.scorecards.inactive_release_forward_shadow",
        "active",
        "Exact per-instant inactive-release replay, recorded-production comparison, and first-pipeline-divergence evidence.",
    ),
    SchemaSpec(
        "off_machine_backup_proof",
        "off_machine_backup_proof_v0.1",
        "weather.reporting.serving_gates.production_readiness_gate",
        "active",
        "Off-machine canonical-evidence backup coverage and checksum verification proof.",
    ),
    SchemaSpec(
        "storage_restore_drill",
        "storage_restore_drill_v0.1",
        "weather.reporting.serving_gates.production_readiness_gate",
        "active",
        "Off-machine restore, checksum verification, scoring, and release-input reproduction drill.",
    ),
    SchemaSpec(
        "challenger_forward_evidence",
        "challenger_forward_evidence_v0.1",
        "weather.reporting.serving_gates.production_readiness_gate",
        "active",
        "Frozen-release forward challenger evidence over fleet-date-blocked market-days.",
    ),
    SchemaSpec(
        "paper_execution_evidence",
        "paper_execution_evidence_v0.1",
        "weather.reporting.serving_gates.production_readiness_gate",
        "active",
        "Countable paper execution evidence with real depth, fees, slippage, and settlement reconciliation.",
    ),
    SchemaSpec(
        "capital_canary_evidence",
        "capital_canary_evidence_v0.1",
        "weather.reporting.serving_gates.production_readiness_gate",
        "active",
        "Reviewed capital-canary readiness proof; never grants credentials or order permissions by itself.",
    ),
    SchemaSpec(
        "release_semantic_contract",
        "release_semantic_contract_v0.1",
        "weather.release_contract",
        "active",
        "Immutable semantic inventory for model, calibration, routing, feature, settlement, and configuration inputs.",
    ),
    SchemaSpec(
        "candidate_input_leakage_audit",
        "candidate_input_leakage_audit_v0.1",
        "weather.model.feature_safety",
        "active",
        "Recursive leakage and point-in-time safety audit over candidate training and evaluation inputs.",
    ),
    SchemaSpec(
        "release_training_evaluation_corpus",
        "release_training_evaluation_corpus_v0.1",
        "weather.operations.release_candidate_contract",
        "active",
        "Frozen training and evaluation corpus lineage, hashes, and fleet-date bounds for a release candidate.",
    ),
    SchemaSpec(
        "pooled_training_evaluation_corpus",
        "pooled_training_evaluation_corpus_v0.1",
        "weather.model.corpus_lineage",
        "active",
        "Frozen point-in-time pooled training and evaluation corpus lineage and fleet-date bounds.",
    ),
    SchemaSpec(
        "pooled_feature_serving_schema",
        "pooled_feature_serving_schema_v0.1",
        "weather.operations.release_candidate_contract",
        "active",
        "Frozen ordered feature contract consumed by pooled model serving.",
    ),
    SchemaSpec(
        "pooled_imputer_metadata",
        "pooled_imputer_metadata_v0.1",
        "weather.operations.release_candidate_contract",
        "active",
        "Frozen pooled imputer identity and semantic metadata.",
    ),
    SchemaSpec(
        "pooled_calibrator_metadata",
        "pooled_calibrator_metadata_v0.1",
        "weather.operations.release_candidate_contract",
        "active",
        "Frozen pooled probability calibrator identity and semantic metadata.",
    ),
    SchemaSpec(
        "pooled_postprocessor_metadata",
        "pooled_postprocessor_metadata_v0.1",
        "weather.operations.release_candidate_contract",
        "active",
        "Frozen pooled probability postprocessor identity and semantic metadata.",
    ),
    SchemaSpec(
        "release_market_route_table",
        "release_market_route_table_v0.1",
        "weather.operations.release_candidate_contract",
        "active",
        "Frozen per-market model, calibration, postprocessing, and unit routing table.",
    ),
    SchemaSpec(
        "base_model_serving_graph",
        "base_model_serving_graph_v0.1",
        "weather.operations.release_candidate_contract",
        "active",
        "Complete release-bound per-market base-model and calibration serving graph.",
    ),
    SchemaSpec(
        "verified_release_pickle_binding",
        "verified_release_pickle_binding_v0.1",
        "weather.release_serving",
        "active",
        "In-process marker for a pickle payload re-hashed and loaded through a verified immutable release binding.",
    ),
    SchemaSpec(
        "release_settlement_rules",
        "release_settlement_rules_v0.1",
        "weather.operations.release_candidate_contract",
        "active",
        "Frozen per-market settlement units, bands, and labeling rules.",
    ),
    SchemaSpec(
        "point_in_time_materializer",
        "point_in_time_materializer_v0.1",
        "weather.reporting.validation.point_in_time_evaluation",
        "active",
        "Leakage-safe point-in-time analytical-table materializer contract.",
    ),
    SchemaSpec(
        "point_in_time_analytical_contract",
        "point_in_time_analytical_contract_v0.1",
        "weather.reporting.validation.point_in_time_evaluation",
        "active",
        "Canonical point-in-time row table and immutable derived-materialization manifest.",
    ),
    SchemaSpec(
        "point_in_time_validation_plan",
        "point_in_time_validation_plan_v0.1",
        "weather.reporting.validation.point_in_time_evaluation",
        "active",
        "Nested fleet-date rolling-origin validation plan with a predeclared calendar embargo.",
    ),
    SchemaSpec(
        "production_point_in_time_preselection",
        "production_point_in_time_preselection_v1",
        "weather.reporting.validation.point_in_time_evaluation",
        "active",
        "Self-hashed candidate-independent selection universe and evaluation-window lock created before production fitting.",
    ),
    SchemaSpec(
        "production_point_in_time_preselection_source",
        "production_point_in_time_preselection_source_v1",
        "weather.reporting.validation.point_in_time_evaluation",
        "active",
        "Narrow manifest-pinned population source created before any candidate model or release identity exists.",
    ),
    SchemaSpec(
        "point_in_time_staging_receipt",
        "point_in_time_staging_receipt_v0.1",
        "weather.operations.point_in_time_staging_receipt",
        "active",
        "Self-hashed staged-source trio binding to the exact latest complete-grade Toronto ledger revisions.",
    ),
    SchemaSpec(
        "release_admissibility_receipt",
        "release_admissibility_receipt_v1",
        "weather.operations.release_admissibility_clock",
        "active",
        "Self-hashed per-market-day proof that immutable settlement and captured-input evidence is release-admissible.",
    ),
    SchemaSpec(
        "release_admissibility_clock",
        "release_admissibility_clock_v1",
        "weather.operations.release_admissibility_clock",
        "active",
        "Small receipt-only collapse of the calendar-contiguous release-admissible streak.",
    ),
    SchemaSpec(
        "all_shadow_release_bootstrap_receipt",
        "all_shadow_release_bootstrap_receipt_v1",
        "weather.operations.all_shadow_release_bootstrap",
        "active",
        "Self-hashed proof for a reviewed research-only all-shadow immutable release build that leaves the active pointer absent.",
    ),
    SchemaSpec(
        "point_in_time_candidate_training_graph",
        "point_in_time_candidate_training_graph_v1",
        "weather.reporting.validation.point_in_time_evaluation",
        "active",
        "Hash-linked production candidate graph binding trainer evidence, fitted artifacts, routing, source replay, and selection exclusions.",
    ),
    SchemaSpec(
        "point_in_time_fit_receipt",
        "point_in_time_fit_receipt_v0.1",
        "weather.reporting.validation.point_in_time_evaluation",
        "active",
        "Hash-linked proof that one preprocessing/model stage fit one declared training-only fold.",
    ),
    SchemaSpec(
        "point_in_time_streaming_evaluation",
        "point_in_time_streaming_evaluation_v0.1",
        "weather.reporting.validation.point_in_time_evaluation",
        "active",
        "Bounded market-day evaluator with isolated evidence lanes and date-clustered intervals.",
    ),
    SchemaSpec(
        "capture_resource_gate",
        "capture_resource_gate_v0.1",
        "weather.operations.capture_resource_gate",
        "active",
        "Read-only admission gate for heavyweight work on live-capture hosts.",
    ),
    SchemaSpec(
        "capture_resource_admission_enforcement",
        "capture_resource_admission_enforcement_v0.1",
        "weather.operations.capture_resource_gate",
        "active",
        "Persisted consumer-specific proof that a heavyweight pipeline enforced its capture-host admission decision before launch.",
    ),
    SchemaSpec(
        "live_variant_predictions",
        "live_variant_predictions_v0.2",
        "weather.collection.live_variant_predictions",
        "active",
        "Live variant tape with verified immutable release lineage and canonical captured-input hash.",
        supersedes=("live_variant_predictions_v0.1",),
        migration_notes=(
            "Legacy v0.1 rows remain readable but cannot satisfy strict release/replay parity gates.",
        ),
    ),
    SchemaSpec(
        "replay_inputs",
        "toronto_replay_inputs_v0.2",
        "weather.collection.snapshot_store",
        "active",
        "Captured-input replay payload with verified immutable release lineage and canonical self-verifiable hash.",
        supersedes=("toronto_replay_inputs_v0.1",),
        migration_notes=(
            "Legacy v0.1 payloads remain replayable but lack strict release/hash parity evidence.",
        ),
    ),
    SchemaSpec(
        "live_variant_settlement_scorecard",
        "live_variant_settlement_scorecard_v0.1",
        "weather.reporting.scorecards.live_variant_settlement_scorecard",
        "active",
        "Canonical settled live-variant probability scoring and captured-input replay parity contract.",
    ),
    SchemaSpec(
        "density_live_replay_parity",
        "density_live_replay_parity_v0.1",
        "weather.operations.density_live_replay_parity",
        "active",
        "Bounded forensic comparison of recorded density tape, legacy live routing, and canonical captured-input replay.",
    ),
    SchemaSpec(
        "clean_day_ledger",
        "clean_day_ledger_v0.1",
        "weather.operations.production_evidence_ledgers",
        "active",
        "Hash-chained append-only closed fleet-day qualification evidence for the production shadow gate.",
    ),
    SchemaSpec(
        "unattended_cycle_ledger",
        "unattended_cycle_ledger_v0.1",
        "weather.operations.production_evidence_ledgers",
        "active",
        "Hash-chained append-only daily/nightly unattended-cycle qualification evidence.",
    ),
    SchemaSpec(
        "production_readiness_gate",
        "production_readiness_gate_v0.1",
        "weather.reporting.serving_gates.production_readiness_gate",
        "active",
        "Hash-linked fail-closed parent gate classifying the highest permitted immutable-release production stage.",
    ),
    SchemaSpec(
        "skill_gap_decomposition",
        "skill_gap_decomposition_v0.1",
        "weather.reporting.research.skill_gap_decomposition",
        "active",
        "Read-only exact CORP/Murphy model-versus-market Brier decomposition, hour and lead-time cuts, and worst-loss taxonomy.",
    ),
    SchemaSpec(
        "profit_edge_analysis",
        "profit_edge_analysis_v0.1",
        "weather.reporting.research.profit_edge_analysis",
        "active",
        "Read-only settled market-uncertainty, realistic-fee, naive-taker liability, and historical exploitability diagnostic.",
    ),
    SchemaSpec(
        "storage_pressure_policy",
        "storage_pressure_policy_v0.1",
        "weather.market.storage_pressure_policy",
        "active",
        "Default-preserving capture flag for the rebuildable full-depth order-book CSV projection.",
    ),
    SchemaSpec(
        "replay_cache_retention",
        "replay_cache_retention_v0.1",
        "weather.operations.replay_cache_retention",
        "active",
        "Reachability-only replay-cache cleanup plans and exact-file action receipts.",
    ),
    SchemaSpec(
        "replay_cache_retention_receipt",
        "replay_cache_retention_receipt_v1",
        "weather.operations.replay_cache_retention",
        "active",
        "Per-action exact-file deletion receipt for reviewed replay-cache cleanup.",
    ),
    SchemaSpec(
        "replay_cache_rebuild_one_parity",
        "replay_cache_rebuild_one_parity_v1",
        "weather.operations.replay_cache_retention",
        "active",
        "Operator-supplied fixture payload comparison across cache-consumed fields.",
    ),
    SchemaSpec(
        "replay_cache_cache_off_rebuild_parity",
        "replay_cache_cache_off_rebuild_parity_v1",
        "weather.operations.replay_cache_retention",
        "active",
        "Apply-bound cache-off recomputation proof across every exact rebuild binding.",
    ),
    SchemaSpec(
        "closed_day_projection_tiering",
        "closed_day_projection_tiering_v0.1",
        "weather.operations.closed_day_projection_tiering",
        "active",
        "Closed-day projection-family registry, gzip plans, and verified action receipts.",
    ),
    SchemaSpec(
        "closed_day_projection_tiering_plan",
        "closed_day_projection_tiering_plan_v0.1",
        "weather.operations.closed_day_projection_tiering",
        "active",
        "Dry-run exact-file manifest for finalized closed-day projection tiering.",
    ),
    SchemaSpec(
        "closed_day_projection_tiering_receipt",
        "closed_day_projection_tiering_receipt_v0.1",
        "weather.operations.closed_day_projection_tiering",
        "active",
        "Per-action compression, preflight, re-verification, and deletion receipt.",
    ),
    SchemaSpec(
        "closed_day_projection_rebuild",
        "closed_day_projection_rebuild_v0.1",
        "weather.operations.closed_day_projection_tiering",
        "active",
        "Rebuild-one byte-parity proof from canonical full-book JSONL.",
    ),
    SchemaSpec(
        "observed_floor_safety_monitor",
        "observed_floor_safety_monitor_v0.1",
        "weather.reporting.source_gates.observed_floor_safety_monitor",
        "active",
        "Fail-closed settled-day join of captured served hard floors to eventual settlement.",
    ),
)
