"""R-STAT-T3: statistics refuter for T3 t3-r3 (floor + remaining rise). Development only.

Independent scoring (own floor mask, own Brier, own cell means) of the t3-r3 candidate generated by
t3_baselines.build(); independent intervals (W replicate, own crossed bootstrap with a different seed,
date-only and market-only cluster bootstraps, two-way cluster-robust normal interval, 11-market t),
multiplicity from the registry, availability-vs-outcome association, per-market / per-week signs,
leave-one-market-out and leave-one-week-out. Registers no rules; scores nothing new (re-scores t3-r3/r3s).

Run: cd C:\\pt\\swarm; <repo python> -m tools.research.model_parity.r-stat-t3_refute  (module name has a
dash, so run as a file: python tools\\research\\model_parity\\r-stat-t3_refute.py with C:\\pt\\swarm on path)
"""
from __future__ import annotations

import json
import math
import sys
from pathlib import Path

sys.path.insert(0, r"C:\pt\swarm")
import numpy as np
import pandas as pd

from tools.research.model_parity import harness as h
from tools.research.model_parity import t3_baselines as t3

OUT = Path(r"C:\swarm\out\refute-stat-t3")
CACHE = Path(r"C:\swarm\cache")
REG = Path(r"C:\swarm\registry.jsonl")
BLOCKS = {"00-05": (0, 5), "06-09": (6, 9), "10-12": (10, 12), "13-16": (13, 16), "17-23": (17, 23),
          "00-16": (0, 16), "all": (0, 23)}
FROM = "from_20260823"
BEFORE = "before_20260823"
SEED2 = 777123  # deliberately different from the harness seed


def candidate_frames():
    OUT.mkdir(parents=True, exist_ok=True)
    out = {}
    for lag, name in ((0, "r3"), (60, "r3s")):
        f = OUT / f"cand_{name}.parquet"
        if f.exists():
            out[name] = pd.read_parquet(f)
            continue
        cands, _ = t3.build(extra_lag_min=lag)
        cands["t3-r3"].to_parquet(f)
        out[name] = cands["t3-r3"]
    return out


def own_snapshot_losses(cand):
    """Own floor mask + renormalisation + Brier; returns per-snapshot frame."""
    s = pd.read_parquet(CACHE / "snapshots.parquet")
    b = pd.read_parquet(CACHE / "bands.parquet")
    assert (s.date <= "2026-09-29").all() and (b.date <= "2026-09-29").all()
    fl = s[["guidance_physical_floor", "high_so_far", "trusted_current_max"]].astype(float).max(axis=1, skipna=True)
    s = s.assign(myfloor=fl)
    b = b.merge(s[["row_key", "myfloor"]], on="row_key", how="left", sort=False)
    bucket = np.floor(b.myfloor.to_numpy() + 0.5)
    imp = (b.kind.to_numpy() != "gte") & (b.high.to_numpy() < bucket)
    imp = np.where(np.isnan(b.myfloor.to_numpy()), False, imp)
    agree = float((imp == b.floor_impossible.to_numpy(bool)).mean())
    c = cand.rename(columns={"p": "pc"})
    b = b.merge(c, on=["row_key", "band_index"], how="left", sort=False)
    b["pc_f"] = np.where(imp, 0.0, b.pc)
    g = b.groupby("row_key", sort=False)
    tot = g.pc_f.transform("sum")
    has = g.pc.transform(lambda x: x.notna().all())
    use = has & b.myfloor.notna() & (tot > 0)
    p = np.where(use, b.pc_f / tot.where(tot > 0, 1.0), b.p_served)
    y = b.is_winner.astype(float).to_numpy()
    b["se_c"] = (p - y) ** 2
    b["se_s"] = (b.p_served - y) ** 2
    b["se_m"] = (b.p_market_yes - y) ** 2
    b["use"] = use
    snap = b.groupby("row_key", sort=False).agg(se_c=("se_c", "mean"), se_s=("se_s", "mean"),
                                                se_m=("se_m", "mean"), use=("use", "first"))
    snap = snap.join(s.set_index("row_key")[["date", "market", "stratum", "local_hour", "settlement_high",
                                             "myfloor", "high_so_far"]])
    return snap.reset_index(), agree


def cells(snap, block, stratum=None, matched=False):
    lo, hi = BLOCKS[block]
    x = snap[(snap.local_hour >= lo) & (snap.local_hour <= hi)]
    if stratum:
        x = x[x.stratum == stratum]
    if matched:
        x = x[x.use]
    c = x.groupby(["date", "market"], sort=True)[["se_c", "se_s", "se_m"]].mean().reset_index()
    c["delta"] = c.se_c - c.se_s
    c["gap"] = c.se_s - c.se_m
    return c


def crossed_boot(c, draws=4000, seed=SEED2):
    rng = np.random.default_rng(seed)
    dates = np.sort(c.date.unique()); mkts = np.sort(c.market.unique())
    di = np.searchsorted(dates, c.date.to_numpy()); mi = np.searchsorted(mkts, c.market.to_numpy())
    wd = rng.multinomial(len(dates), np.full(len(dates), 1 / len(dates)), size=draws).astype(float)
    wm = rng.multinomial(len(mkts), np.full(len(mkts), 1 / len(mkts)), size=draws).astype(float)
    w = wd[:, di] * wm[:, mi]
    num = w @ c.delta.to_numpy(); den = w.sum(1)
    est = num[den > 0] / den[den > 0]
    return np.quantile(est, [.025, .975]).tolist(), float(est.std(ddof=1))


def one_way_boot(c, key, draws=4000, seed=SEED2 + 1):
    rng = np.random.default_rng(seed)
    u = np.sort(c[key].unique()); ix = np.searchsorted(u, c[key].to_numpy())
    w = rng.multinomial(len(u), np.full(len(u), 1 / len(u)), size=draws).astype(float)[:, ix]
    est = (w @ c.delta.to_numpy()) / w.sum(1)
    return np.quantile(est, [.025, .975]).tolist(), float(est.std(ddof=1))


def cgm_se(c):
    """Two-way (date, market) cluster-robust SE of the equal-cell mean."""
    e = c.delta.to_numpy() - c.delta.mean(); n = len(e)
    vd = c.assign(e=e).groupby("date").e.sum().pow(2).sum()
    vm = c.assign(e=e).groupby("market").e.sum().pow(2).sum()
    vc = (e ** 2).sum()
    return math.sqrt(max(vd + vm - vc, vc) ) / n


def w_replicate(c):
    d = h.data()
    idx = np.array([d.key_index[(a, b)] for a, b in zip(c.date, c.market)])
    sub = d.w[:, idx]
    est = (sub @ c.delta.to_numpy()) / sub.sum(1)
    return float(c.delta.mean()), np.quantile(est, [.025, .975]).tolist(), float(est.std(ddof=1))


def week_of(date):
    return pd.to_datetime(date).dt.strftime("%G-W%V")


def analyse_block(snap, block, n_family):
    cf = cells(snap, block, FROM); cb = cells(snap, block, BEFORE); cm = cells(snap, block, FROM, matched=True)
    est, wci, wsd = w_replicate(cf)
    xci, xsd = crossed_boot(cf)
    dci, dsd = one_way_boot(cf, "date")
    mci, msd = one_way_boot(cf, "market")
    se2 = cgm_se(cf)
    pm = cf.groupby("market").delta.mean()
    tstat = pm.mean() / (pm.std(ddof=1) / math.sqrt(len(pm)))
    from scipy import stats as ss  # noqa
    t_ci = [pm.mean() + q * pm.std(ddof=1) / math.sqrt(len(pm)) for q in ss.t.ppf([.025, .975], len(pm) - 1)]
    sign_p = float(ss.binomtest(int((pm < 0).sum()), len(pm), 0.5).pvalue)
    zb = ss.norm.ppf(1 - 0.025 / n_family)
    sd_max = max(wsd, xsd, se2)
    bonf = [est - zb * sd_max, est + zb * sd_max]
    gap = float(cf.gap.mean())
    # leave-one-market-out / leave-one-week-out (equal-cell mean)
    lomo = {m: float(cf[cf.market != m].delta.mean()) for m in sorted(cf.market.unique())}
    cf = cf.assign(week=week_of(cf.date))
    pw = cf.groupby("week").agg(delta=("delta", "mean"), cells=("delta", "size"))
    lowo = {w: float(cf[cf.week != w].delta.mean()) for w in pw.index}
    # concentration: share of total delta from most negative k cells / single market / single week
    tot = cf.delta.sum()
    srt = np.sort(cf.delta.to_numpy())
    conc = {"top5_cells_share": float(srt[:5].sum() / tot), "top10_cells_share": float(srt[:10].sum() / tot),
            "top_market_share": float(cf.groupby("market").delta.sum().min() / tot),
            "top_week_share": float(cf.groupby("week").delta.sum().min() / tot),
            "cells_negative": int((cf.delta < 0).sum()), "cells": int(len(cf)),
            "dates_negative": int((cf.groupby("date").delta.mean() < 0).sum()), "dates": int(cf.date.nunique())}
    # LEAD conditions under independent computation (worst of the interval methods)
    hi_worst = max(wci[1], xci[1], dci[1], mci[1], est + 1.96 * se2, t_ci[1])
    lead_ind = {"interval_excludes_0_all_methods": bool(hi_worst < 0),
                "size": bool(est <= -0.0133 or est <= -0.05 * gap),
                "both_strata_negative": bool(est < 0 and cb.delta.mean() < 0),
                "markets_negative_ge8": bool((pm < 0).sum() >= 8),
                "lomo_all_lead_size": bool(all(v <= -0.0133 or v <= -0.05 * gap for v in lomo.values())),
                "lowo_all_lead_size": bool(all(v <= -0.0133 or v <= -0.05 * gap for v in lowo.values())),
                "bonferroni_excludes_0": bool(bonf[1] < 0)}
    return {"block": block, "from_estimate": est, "before_estimate": float(cb.delta.mean()),
            "matched_from_estimate": float(cm.delta.mean()), "from_gap": gap, "five_pct_bar": -0.05 * gap,
            "cells_from": int(len(cf)),
            "ci_W_replicate": wci, "ci_crossed_seed2": xci, "ci_date_cluster": dci, "ci_market_cluster": mci,
            "ci_cgm_2way_normal": [est - 1.96 * se2, est + 1.96 * se2], "ci_market_t10": t_ci,
            "sd": {"W": wsd, "crossed2": xsd, "date": dsd, "market": msd, "cgm": se2},
            "bonferroni": {"family": n_family, "z": float(zb), "ci": bonf},
            "market_t": float(tstat), "sign_test_p": sign_p,
            "per_market": {k: float(v) for k, v in pm.items()},
            "markets_negative": int((pm < 0).sum()),
            "per_week": {k: {"delta": float(r.delta), "cells": int(r.cells)} for k, r in pw.iterrows()},
            "leave_one_market_out": lomo, "leave_one_week_out": lowo, "concentration": conc,
            "lead_conditions_independent": lead_ind,
            "independent_class": "LEAD" if all(lead_ind[k] for k in ("interval_excludes_0_all_methods", "size",
                                                                     "both_strata_negative", "markets_negative_ge8"))
            else ("WEAK" if est < 0 else "NULL/HARM")}


def availability_vs_outcome(snap, rowcounts):
    """Is coverage (or METAR completeness) associated with the realised outcome?"""
    res = {}
    s = snap.copy()
    s["rise_realised"] = s.settlement_high - s.myfloor  # label used ONLY here, as a refuter diagnostic
    s = s.join(rowcounts, on="row_key")
    for block in ("13-16", "17-23", "00-05", "all"):
        lo, hi = BLOCKS[block]
        x = s[(s.local_hour >= lo) & (s.local_hour <= hi) & (s.stratum == FROM)]
        cov, unc = x[x.use], x[~x.use]
        r = {"snapshots": int(len(x)), "fallback_share": float((~x.use).mean()),
             "covered": {"served_brier": float(cov.se_s.mean()), "market_brier": float(cov.se_m.mean()),
                         "gap": float((cov.se_s - cov.se_m).mean()), "rise_realised_mean": float(cov.rise_realised.mean())},
             "fallback": ({"served_brier": float(unc.se_s.mean()), "market_brier": float(unc.se_m.mean()),
                           "gap": float((unc.se_s - unc.se_m).mean()),
                           "rise_realised_mean": float(unc.rise_realised.mean())} if len(unc) else None)}
        # METAR completeness: missing routine rows relative to the station-hour mode
        if "missing" in x:
            full, gappy = x[x.missing <= 0], x[x.missing >= 2]
            r["metar_complete"] = {"n": int(len(full)), "delta": float((full.se_c - full.se_s).mean()),
                                   "rise_realised_mean": float(full.rise_realised.mean())}
            r["metar_gappy_ge2"] = {"n": int(len(gappy)),
                                    "delta": float((gappy.se_c - gappy.se_s).mean()) if len(gappy) else None,
                                    "rise_realised_mean": float(gappy.rise_realised.mean()) if len(gappy) else None}
            r["corr_missing_vs_rise"] = float(np.corrcoef(x.missing.fillna(0), x.rise_realised.fillna(0))[0, 1]) \
                if x.missing.std() > 0 else None
        res[block] = r
    return res


def metar_rowcounts():
    """Count routine rows available at t for today (independent re-derivation via t3.pit_asof)."""
    snaps, _ = h.candidate_inputs()
    m = t3.load_metar(0)
    today = t3.pit_asof(snaps, m, "today")
    s = snaps.set_index("row_key")[["station", "local_hour"]].join(today)
    s["cumn"] = s.cumn.fillna(0)
    # expected rows by local hour: median count over all snapshots of that station-hour
    exp = s.groupby(["station", "local_hour"]).cumn.transform("median")
    s["missing"] = exp - s.cumn
    # independent check of running max vs captured high_so_far late in the day
    return s[["missing", "cummax"]]


def main():
    assert not Path(r"C:\swarm\STOP").exists()
    reg = [json.loads(x) for x in REG.read_text(encoding="utf-8-sig").splitlines() if x.strip()]
    n_family = len(reg)
    cands = candidate_frames()
    result = {"agent": "r-stat-t3", "development": True, "HARNESS_SHA256": h.harness_sha256(),
              "registry_rules_at_run": n_family,
              "registry_by_agent": pd.Series([r["agent"] for r in reg]).value_counts().to_dict(),
              "registry_controls_or_sensitivities": [r["id"] for r in reg if any(
                  k in r["text"][:120].lower() for k in ("control", "sensitivity", "diagnostic"))]}
    rc = metar_rowcounts()
    for name, cand in cands.items():
        snap, agree = own_snapshot_losses(cand)
        assert (snap.date <= "2026-09-29").all()
        result[name] = {"floor_mask_agreement_with_harness": agree,
                        "rows_after_20260929": int((snap.date > "2026-09-29").sum()),
                        "blocks": {b: analyse_block(snap, b, n_family) for b in BLOCKS}}
        if name == "r3":
            result[name]["availability_vs_outcome"] = availability_vs_outcome(snap, rc)
            # running max vs captured high_so_far (17-23, from)
            j = snap.set_index("row_key").join(rc)
            late = j[(j.local_hour >= 17) & (j.stratum == FROM)]
            result[name]["runmax_minus_high_so_far_17_23"] = {
                "mean": float((late["cummax"] - late.high_so_far).mean()),
                "share_equal": float((late["cummax"] == late.high_so_far).mean()),
                "share_runmax_ge_settlement": float((late["cummax"] >= late.settlement_high).mean())}
    (OUT / "result.json").write_text(json.dumps(result, indent=1, default=float), encoding="utf-8")
    print(json.dumps({k: result[k] for k in ("registry_rules_at_run",)}))
    for name in cands:
        for b, r in result[name]["blocks"].items():
            print(name, b, r["independent_class"], round(r["from_estimate"], 5), r["ci_W_replicate"],
                  r["ci_crossed_seed2"], r["ci_date_cluster"], r["ci_market_cluster"], r["ci_market_t10"],
                  r["bonferroni"]["ci"], r["markets_negative"], r["lead_conditions_independent"])


if __name__ == "__main__":
    main()
