"""Shared quote configuration values, independent of policy implementation."""
from weather.paths import config_path, data_path
DEFAULT_INFORMATION_EVENT_CALENDAR = config_path() / "info_event_calendar.json"
DEFAULT_CLOB_RECON = data_path() / "backtest" / "clob_book_recon.json"

POLICY_VERSION = "mm_policy_v0.2"


DEFAULT_POLICY_CONFIG = {
    "policy_version": POLICY_VERSION,
    "tick_size": 0.001,
    "min_price": 0.001,
    "max_price": 0.999,
    "quote_size": 5.0,
    "harvest_half_spread": 0.01,
    "max_book_age_seconds": 120.0,
    "max_model_age_seconds": 900.0,
    "max_watcher_age_seconds": 120.0,
    "max_harvest_spread": 0.08,
    "max_edge_spread": 0.12,
    "min_depth_1pct_total": 1.0,
    "shadow_disagreement_stand_down": 0.08,
    "edge_min_advantage": 0.03,
    "edge_fee_buffer": 0.005,
    "adverse_selection_buffer": 0.01,
    "max_event_notional": 25.0,
    "max_band_notional": 10.0,
    "max_correlated_regime_notional_usdc": 0.0,
    "max_correlated_regime_joint_loss_usdc": 0.0,
    "correlated_regime_market_groups": "",
    "max_daily_loss": 25.0,
    "information_event_calendar_enabled": True,
    "information_event_calendar_path": str(DEFAULT_INFORMATION_EVENT_CALENDAR),
    "event_gate_widen_buffer": 0.01,
    "event_gate_exception_enabled": False,
    "event_gate_exception_event_classes": "",
    "event_gate_exception_evidence_status": "",
    "event_gate_exception_evidence_id": "",
    "event_gate_exception_risk_cap_usdc": 0.0,
    "clob_recon_policy_enabled": True,
    "clob_recon_path": str(DEFAULT_CLOB_RECON),
    "hourly_trust_multiplier_00_08": 0.35,
    "hourly_trust_multiplier_09_14": 0.85,
    "hourly_trust_multiplier_15_19": 1.0,
    "hourly_trust_multiplier_20_23": 0.75,
    "early_hour_guardrail_enabled": True,
    "early_hour_guardrail_market_weight": 0.35,
    "early_hour_guardrail_size_multiplier": 0.35,
    "early_hour_guardrail_quote_widen_buffer": 0.01,
    "early_hour_guardrail_min_edge_multiplier": 1.5,
    "early_hour_guardrail_override_min_edge": 0.10,
    "early_hour_guardrail_override_source_states": "all_fresh",
    "early_hour_guardrail_override_count_buckets": "normal_count,high_count,full_count",
    "early_hour_guardrail_override_disagreement_buckets": "low_disagreement,moderate_disagreement",
    "early_hour_guardrail_override_max_forecast_disagreement": 1.5,
    "snapshot_cadence_quality_enabled": True,
    "max_snapshot_cadence_gap_seconds": 900.0,
    "snapshot_cadence_stale_model_seconds": 900.0,
    "snapshot_cadence_confidence_haircut": 0.75,
    "snapshot_cadence_degraded_permission": "deny",
    "snapshot_cadence_quote_size_multiplier": 0.5,
    "snapshot_cadence_quote_widen_buffer": 0.01,
    "current_high_trust_gate_enabled": True,
    "current_high_trust_gate_start_hour_local": 15,
    "current_high_trust_gate_edge_action": "deny",
    "current_high_trust_gate_harvest_size_multiplier": 0.5,
    "current_high_trust_gate_quote_widen_buffer": 0.01,
    "maker_model_variant_basket_enabled": True,
    "maker_model_variant_basket_id": "maker_default_v0",
    "maker_model_variant_paths": "",
    "maker_model_variant_ids": "",
    "maker_model_variant_max_external_rows": 250000,
}
