"""Generate the correspondence inventory from source text and Git addition history."""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path
from urllib.parse import quote

from weather.paths import REPO_ROOT

OUTPUT = "docs/roadmap/correspondence-index.md"
NAME_RE = re.compile(
    r"^(workstation-handoff|agent-report|agent-work-order)-"
    r"(\d{4}-\d{2}-\d+[a-z]*)(?:-.*)?\.md$"
)
KINDS = {"workstation-handoff": "handoff", "agent-report": "report", "agent-work-order": "work order"}
SECTION_ID = r"\d+[a-z]*(?:-bis)?"
EF_RE = re.compile(
    rf"\b(?:EF|ESTABLISHED_FINDINGS(?:\.md)?)\s*§\s*{SECTION_ID}"
    rf"(?:\s*(?:,|and|&)\s*§\s*{SECTION_ID})*", re.I,
)


def ef_sections(text: str) -> list[str]:
    """Include shorthand continuations (EF §1, §1c), but never RF/HW sections."""
    prose = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text).replace("`", "").replace("*", "")
    sections = {section.lower() for group in EF_RE.findall(prose)
                for section in re.findall(rf"§\s*({SECTION_ID})", group, re.I)}
    sections.update(re.findall(rf"ESTABLISHED_FINDINGS\.md#({SECTION_ID})(?=-|\))", text, re.I))
    return sorted(sections, key=lambda section: (int(re.match(r"\d+", section)[0]), section))


def git_added_dates(repo_root: Path) -> dict[str, str]:
    """One bounded history query; never substitute filename dates or the clock."""
    def git(*args: str) -> str:
        result = subprocess.run(
            ["git", "-C", str(repo_root), *args], capture_output=True,
            text=True, encoding="utf-8", check=False,
        )
        if result.returncode:
            raise ValueError(f"correspondence history unavailable: {result.stderr.strip()}")
        return result.stdout

    if git("rev-parse", "--is-shallow-repository").strip() == "true":
        raise ValueError("correspondence history is shallow; fetch full history before generation/check")
    history = git(
        "-c", "core.quotepath=false", "log", "--reverse", "--diff-filter=A",
        "--no-renames", "--format=@%ad", "--date=short", "--name-only", "--",
        "docs/roadmap/workstation-handoff-*.md", "docs/roadmap/agent-report-*.md",
        "docs/roadmap/agent-work-order-*.md",
    )
    dates: dict[str, str] = {}
    date = ""
    for line in history.splitlines():
        if re.fullmatch(r"@\d{4}-\d{2}-\d{2}", line):
            date = line[1:]
        elif line.startswith("docs/roadmap/") and date:
            dates.setdefault(line, date)
    return dates


def correspondence_rows(repo_root: Path, dates: dict[str, str]) -> list[dict[str, str]]:
    rows = []
    for path in sorted((repo_root / "docs/roadmap").glob("*.md")):
        match = NAME_RE.fullmatch(path.name)
        if not match:
            if path.name.startswith(tuple(f"{prefix}-" for prefix in KINDS)):
                raise ValueError(f"unparseable correspondence filename: {path.name}")
            continue
        text = path.read_text(encoding="utf-8-sig")
        title = re.search(r"^#\s+(.+?)\s*#*\s*$", text, re.M)
        items = set(re.findall(r"\bitem-(\d+)(?:-|\b)", text, re.I))
        for group in re.findall(r"\bitems?\s+\d+(?:\s*[,/]\s*\d+)*", text, re.I):
            items.update(re.findall(r"\d+", group))
        rows.append({
            "name": path.name, "id": match[2], "kind": KINDS[match[1]],
            "title": title[1] if title else "(no H1 in source)",
            "added": dates.get(path.relative_to(repo_root).as_posix(), "uncommitted"),
            "ef": ", ".join(ef_sections(text)) or "—",
            "items": ", ".join(sorted(items, key=int)) or "—",
        })
    # Actual addition date is the chronology. Filenames only break same-day ties.
    return sorted(rows, key=lambda row: (row["added"], row["name"]))


def render_index(repo_root: Path, dates: dict[str, str] | None = None) -> str:
    rows = correspondence_rows(repo_root, git_added_dates(repo_root) if dates is None else dates)
    reports: dict[str, list[str]] = {}
    for row in rows:
        if row["kind"] == "report":
            reports.setdefault(row["id"], []).append(row["name"])

    def cell(text: str) -> str:
        return text.replace("&", "&amp;").replace("|", "&#124;").replace("[", "&#91;").replace("]", "&#93;").replace("<", "&lt;").replace(">", "&gt;")

    def link(name: str, label: str) -> str:
        return f"[{cell(label)}]({quote(name)})"

    lines = [
        "# Correspondence index", "",
        "Generated by `python -m weather.reporting.roadmap.correspondence_index`; do not hand-edit.",
        "Use `--check` for read-only parity. Full Git history is required; added dates are Git author dates,",
        "not mission labels. Uncommitted files are marked until committed; regenerate after their first commit.",
        "Rows sort by added date, then filename. Same-id reports are candidates, not proof of acceptance;",
        "legacy collisions may have several answers. Citations are extracted, not validated historical claims.", "",
        "| Mission id | Type | Title / source | Git-added date | Answering report (same id) | EF sections cited | Items cited |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        answers = "; ".join(link(name, name) for name in reports.get(row["id"], [])) or "none in tree"
        lines.append(f"| {row['id']} | {row['kind']} | {link(row['name'], row['title'])} | {row['added']} | {answers} | {row['ef']} | {row['items']} |")
    return "\n".join(lines) + "\n"


def parity_errors(repo_root: Path) -> list[str]:
    try:
        expected = render_index(repo_root)
    except (OSError, ValueError) as exc:
        return [str(exc)]
    path = repo_root / OUTPUT
    if not path.is_file() or path.read_text(encoding="utf-8-sig") != expected:
        return [f"{OUTPUT}: stale or missing; run python -m weather.reporting.roadmap.correspondence_index"]
    return []


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    root = args.repo_root.resolve()
    if args.check:
        errors = parity_errors(root)
        print("\n".join(errors) if errors else "Correspondence index: OK")
        return int(bool(errors))
    try:
        content = render_index(root)
    except (OSError, ValueError) as exc:
        print(str(exc))
        return 1
    (root / OUTPUT).write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
