"""Canonical CLI and public API for the research-only H1 smoothing sweep."""

from weather.reporting.research.ordinal_smoothing_sweep_impl import (
    BOOTSTRAP_REPLICATES,
    BOOTSTRAP_SEED,
    DETERMINISM_CANARY_DATE,
    MASS_TOLERANCE,
    SCHEMA_VERSION,
    SMOOTHING_SIGMA,
    SWEEP_WEIGHTS,
    ExperimentConfigurationError,
    alignment_gate,
    analyze_holdout_arms,
    analyze_holdout_arms_incremental,
    analyze_tune_arms,
    analyze_tune_arms_incremental,
    analyze_weight_zero_control,
    build_parser,
    build_payload,
    cache_fingerprint,
    cluster_bootstrap_ci,
    exact_determinism_gate,
    exclusive_research_lock,
    folders_for_entries,
    load_or_run_arm,
    main,
    make_ordinal_model_factory,
    mass_gate,
    ordinal_smoothing_config,
    paired_fleet_date_rows,
    paired_summary,
    partition_manifest_entries,
    scope_effect_audit,
    read_predeclared_dates,
    render_report,
    run_arm,
    run_experiment,
    sign_test,
    validate_path_contract,
    validate_staged_daily_inputs,
    write_outputs,
)

__all__ = [
    "BOOTSTRAP_REPLICATES",
    "BOOTSTRAP_SEED",
    "DETERMINISM_CANARY_DATE",
    "MASS_TOLERANCE",
    "SCHEMA_VERSION",
    "SMOOTHING_SIGMA",
    "SWEEP_WEIGHTS",
    "ExperimentConfigurationError",
    "alignment_gate",
    "analyze_holdout_arms",
    "analyze_holdout_arms_incremental",
    "analyze_tune_arms",
    "analyze_tune_arms_incremental",
    "analyze_weight_zero_control",
    "build_parser",
    "build_payload",
    "cache_fingerprint",
    "cluster_bootstrap_ci",
    "exact_determinism_gate",
    "exclusive_research_lock",
    "folders_for_entries",
    "load_or_run_arm",
    "main",
    "make_ordinal_model_factory",
    "mass_gate",
    "ordinal_smoothing_config",
    "paired_fleet_date_rows",
    "paired_summary",
    "partition_manifest_entries",
    "scope_effect_audit",
    "read_predeclared_dates",
    "render_report",
    "run_arm",
    "run_experiment",
    "sign_test",
    "validate_path_contract",
    "validate_staged_daily_inputs",
    "write_outputs",
]


if __name__ == "__main__":
    raise SystemExit(main())
